:sections: [
  {
    id: "html_header",
    text: "Report Header",
    path: "shared/360/mrf_report_header",
    children: [
      {
        id: "html_header_menu",
        text: "Menu",
        path: "shared/reports/mrf/header/menu",
        children: [
          {
            id: "html_header_overview",
            text: "Overview",
            path: "shared/reports/mrf/header/overview"
          },
          {
            id: "html_header_traits",
            text: "Traits",
            path: "shared/reports/mrf/header/traits"
          },
          {
            id: "html_header_scores",
            text: "Scores",
            path: "shared/reports/mrf/header/scores",
          },
          {
            id: "html_header_data_points_competencies",
            text: "Data Point Competencies",
            path: "shared/reports/mrf/header/data_points_competencies",
          },
          {
            id: "html_header_data_points_traits",
            text: "Data Points Traits",
            path: "shared/reports/mrf/header/data_points_traits"
          },
          {
            id: "html_header_summary",
            text: "Summary",
            path: "shared/reports/mrf/header/summary"
          }
        ]
      },
      {
        id: "html_header_download_pdf_link",
        text: "Download PDF Link",
        path: "shared/reports/mrf/header/download_pdf_link"
      }
    ]
  },
  {
    id: "html_cover_page",
    text: "Cover page",
    path: "mrf/assessments/reports/competency_report/html/page1",
    children: [
      {
        id: "html_numerical_aggregate_score",
        text: "Numerical Aggregate Score",
        path: "mrf/assessments/reports/competency_report/html/numerical_aggregate_score",
        locals: {},
        links: {
          html: [],
          pdf: ["pdf_mrf_report_numerical_aggregate_score_compact"]
        }        
      },
      {
        id: "html_show_completion_status",
        text: "Completion Status",
        path: "mrf/assessments/reports/competency_report/html/show_completion_status",
        locals: {},
        links: {
          html: ["html_header_overview"],
          pdf: ["pdf_mrf_report_show_completion_status_compact"]
        }        
      },
      {
        id: "html_mrf_report_cover",
        text: "Report Cover",
        path: "mrf/assessments/reports/competency_report/html/mrf_report_cover",
        locals: {}
      }
    ]
  },
  {
    id: "html_360_degree_scores_competencies",
    text: "360 Degree and Self Ratings on Competencies/Values",
    path: "mrf/assessments/reports/competency_report/html/scores_competencies",
    children: [
      {
      id: "html_360_scores_competency_legend",
        text: "Desired Range on Legend[Show/Hide]",
        path: "mrf/assessments/reports/competency_report/html/desired_range_legend",
        children: [
          {
            id: "html_360_show_desired_range_header",
            text: "Show Desired Range in Legend",
            path: "mrf/assessments/reports/competency_report/html/label_with_desired_range",
            locals: {},
            links: {
              html: ["html_360_show_desired_range_section"],
              pdf: ["pdf_scores_competencies_with_desired_range_compact"]
            }
          },
          {
            id: "html_360_hide_desired_range_header",
            text: "Hide Desired Range in Legend",
            path: "mrf/assessments/reports/competency_report/html/label_without_desired_range",
            locals: {},
            links: {
              html: ["html_360_hide_desired_range_section"],
              pdf: ["pdf_scores_competencies_without_desired_range_compact"]
            }
          }
        ]
      },
      {
        id: "html_360_scores_competency_desired_range",
        text: "Desired Range on Graph [Show/Hide]",
        path: "mrf/assessments/reports/competency_report/html/desired_range_graph",
        children: [
          {
            id: "html_360_show_desired_range_section",
            text: "Show Desired Range in Graph",
            path: "mrf/assessments/reports/competency_report/html/graph_with_desired_range",
            locals: {},
            links: {
              html: ["html_360_show_desired_range_header"],
              pdf: ["pdf_scores_competencies_with_desired_range_compact"]
            }            
          },
          {
            id: "html_360_hide_desired_range_section",
            text: "Hide Desired Range in Graph",
            path: "mrf/assessments/reports/competency_report/html/graph_without_desired_range",
            locals: {},
            links: {
              html: ["html_360_hide_desired_range_header"],
              pdf: ["pdf_scores_competencies_without_desired_range_compact"]
            }            
          }
        ]
      }
    ]
  },
  {
    id: "html_360_degree_scores_traits_under_competencies",
    text: "360 Degree self rating on traits",
    path: "mrf/assessments/reports/competency_report/html/scores_traits_competencies",
    children: [
      {
        id: "html_360_traits_under_competency_legend",
        text: "Trait Score Legend",
        path: "mrf/assessments/reports/competency_report/html/trait_legend",
        children: [
          {
            id: "html_360_trait_scores_legent_with_desired_range",
            text: "Legend with Desired Range",
            path: "mrf/assessments/reports/competency_report/html/trait_scores_legend_with_desired_range",
            locals: {},
            links: {
              html: ["html_360_traits_under_competency_graph_with_desired_range"],
              pdf: ["pdf_trait_scores_under_competencies_with_desired_range"]
            }
          },
          {
            id: "html_360_trait_scores_legent_without_desired_range",
            text: "Legend without Desired Range",
            path: "mrf/assessments/reports/competency_report/html/trait_scores_legend_without_desired_range",
            locals: {},
            links: {
              html: ["html_header_traits","html_360_traits_under_competency_graph_without_desired_range"],
              pdf: ["pdf_trait_scores_under_competencies_without_desired_range"]
            }
          }
        ]
      },
      {
        id: "html_360_traits_under_competency_graph",
        text: "Trait Score Graph",
        path: "mrf/assessments/reports/competency_report/html/trait_graph",
        children: [
          {
            id: "html_360_traits_under_competency_graph_with_desired_range",
            text: "Trait Graph With Desired Range",
            path: "mrf/assessments/reports/competency_report/html/trait_graph_with_desired_range",
            locals: {},
            links: {
              html: ["html_360_trait_scores_legent_with_desired_range"],
              pdf: ["pdf_trait_scores_under_competencies_with_desired_range"]
            }            
          },
          {
            id: "html_360_traits_under_competency_graph_without_desired_range",
            text: "Trait Graph Without Desired Range",
            path: "mrf/assessments/reports/competency_report/html/trait_graph_without_desired_range",
            locals: {},
            links: {
              html: ["html_header_traits","html_360_trait_scores_legent_without_desired_range"],
              pdf: ["pdf_trait_scores_under_competencies_without_desired_range"]
            }            
          }
        ]
      }
    ]
  },
  {
    id: "html_top_bottom_competencies",
    text: "Top 3 and Bottom 3 Competencies",
    path: "mrf/assessments/reports/competency_report/html/top_bottom_competencies",
    children: []
  },
  {
    id: "html_areas_of_improvement",
    text: "Areas of Improvement",
    path: "mrf/assessments/reports/competency_report/html/areas_of_improvement",
    children: []
  },
  {
    id: "html_ratings_on_questions_details",
    text: "Details of 360 Degree Ratings on Questions",
    path: "mrf/assessments/reports/competency_report/html/ratings_on_questions_details",
    children: []
  },
 {
    id: "html_competency_importance_as_per_stakeholders",
    text: "Competency Importance as per Stakeholders",
    path: "mrf/assessments/reports/competency_report/html/competency_importance_as_per_stakeholders",
    children: []
  },
  {
    id: "html_perception_gap_on_traits",
    text: "Perception Gap on Traits",
    path: "mrf/assessments/reports/competency_report/html/perception_gap_on_traits",
    children: [],
    links: {
      html: [],
      pdf: ["pdf_perception_gap_on_traits"]
    }  
  },
  {
    id: "html_360_degree_competencies_scores_in_descending_order",
    text: "360 Degree Ratings on Competencies",
    path: "mrf/assessments/reports/competency_report/html/competencies_descending_order",
    children: [],
    links: {
      html: [],
      pdf: ["pdf_360_degree_competencies_scores_in_descending_order"]
    }    
  },
  {
    id: "html_360_degree_traits_scores_in_descending_order",
    text: "360 Degree Ratings on Traits",
    path: "mrf/assessments/reports/competency_report/html/competencies_traits_descending_order",
    children: [],
    links: {
      html: [],
      pdf: ["pdf_360_degree_traits_scores_in_descending_order"]
    }    
  },
  {
    id: "html_data_points_on_360_degree_scores_competencies",
    text: "Details on 360 Degree Ratings on Competencies/Values",
    path: "mrf/assessments/reports/competency_report/html/competency_wise_frequency_data_points",
    children: [
      {
        id: "html_competencies_textual_data_points",
        text: "Competencies Textual Data Points",
        path: "mrf/assessments/reports/competency_report/html/competencies_textual_data_points",
        locals: {
          competency: "competency",
          competency_scores: "competency_scores"
        }       
      },
      {
        id: "html_competency_wise_best_worst_scores",
        text: "Competencywise best and worst score",
        path: "mrf/assessments/reports/competency_report/html/competency_wise_best_worst_scores",
        locals: {
          competency: "competency",
          competency_scores: "competency_scores"
        }      
      },
      {
        id: "html_competencies_descending_order",
        text: "Overall Scores in descending order",
        path: "mrf/assessments/reports/competency_report/html/descending_overall_competency_score",
        locals: {
          competency: "competency",
          competency_scores: "competency_scores"
        }       
      },
      {
        id: "html_descending_average_competency_rating",
        text: "Average Rating given by Stakeholders ",
        path: "mrf/assessments/reports/competency_report/html/descending_average_competency_rating",
        locals: {
          competency: "competency",
          competency_scores: "competency_scores"
        }      
      },
      {
        id: "html_competency_frequency_rating_table",
        text: "Frequency Rating Table",
        path: "mrf/assessments/reports/competency_report/html/frequency_rating_table_competency",
        locals: {
          competency: "competency",
          competency_scores: "competency_scores",
          role_wise_scores : "competency_scores[:role_wise_scores]",
          trait_wise: "false",
          graph_buckets: "@competency_graph_buckets"
        },
        links: {
          html: ["html_header_data_points_competencies"],
          pdf: []
        }        
      }
    ],
    links: {
      html: [],
      pdf: ["pdf_frequency_rating_table_compact"]
    }
  },
  {
    id: "html_data_points_on_360_degree_scores_traits_under_competencies",
    text: "Details on 360 Degree Ratings on Traits (Under Competencies / Values)",
    path: "mrf/assessments/reports/competency_report/html/trait_wise_frequency_data_points",
    children: [
      {
        id: "html_traits_textual_data_points",
        text: "Traits Textual Data Points",
        path: "mrf/assessments/reports/competency_report/html/traits_textual_data_points",
        locals: {
          trait_score: "trait_score"
        },
        links: {
          html: ["html_header_data_points_traits"],
          pdf: []
        }        
      },
      {
        id: "html_trait_wise_best_worst_scores",
        text: "Visual data points:  Best and Worst scores across exercise",
        path: "mrf/assessments/reports/competency_report/html/trait_wise_best_worst_scores",
        locals: {
          trait_score: "trait_score"
        }        
      },
      {
        id: "html_descending_trait_wise_overall_score",
        text: "Visual data points: Overall Scores in descending order",
        path: "mrf/assessments/reports/competency_report/html/descending_trait_wise_overall_score",
        locals: {
          trait_score: "trait_score"
        }        
      },
      {
        id: "html_descending_trait_wise_average_rating",
        text: "Visual data points: Average Rating given by Stakeholders ",
        path: "mrf/assessments/reports/competency_report/html/descending_trait_wise_average_rating",
        locals: {
          trait_score: "trait_score"
        }        
      },
      {
        id: "html_frequency_rating_table",
        text: "Frequency Rating Table",
        path: "mrf/assessments/reports/competency_report/html/frequency_rating_table_trait",
        locals: {
          trait_score: "trait_score",
          role_wise_scores: "trait_score[:role_wise_scores]",
          trait_wise: "true",
          graph_buckets: "@trait_graph_buckets" 
        },
        links: {
          html: ["html_header_data_points_traits"],
          pdf: []
        }        
      }
    ],
    links: {
      html: [],
      pdf: ["pdf_competency360_traits_data_pts_trait_name_as_title_compact"]
    }
  },
  {
    id: "html_response_distribution_on_questions_new",
    text: "Response Distribution on Questions [6 points]",
    path: "mrf/assessments/reports/competency_report/html/response_distribution_six_points",
    children: [],
    links: {
      html: [],
      pdf: ["pdf_response_distribution_on_questions_new"]
    }    
  },
  {
    id: "html_responses_to_other_questions",
    text: "Response to Other Questions",
    path: "mrf/assessments/reports/competency_report/html/page8",
    children: [
      {
        id: "html_response_others",
        text: "Response to Other Questions [by Stakeholders]",
        path: "mrf/assessments/reports/competency_report/html/responses_by_others",
        locals: "",
        children: [
          {
            id: "html_response_others_with_type_by_stakeholder",
            text: "Show Stakeholder Type",
            path: "mrf/assessments/reports/competency_report/html/show_stakholder_type",
            locals: {},
            links: {
              html: [],
              pdf: ["pdf_responses_with_stakholder_type_others"]
            }            
          },
          {
            id: "html_response_others_without_type_by_stakeholders",
            text: "Hide Stakeholder Type",
            path: "mrf/assessments/reports/competency_report/html/hide_stakholder_type",
            locals: {},
            links: {
              html: [],
              pdf: ["pdf_responses_without_stakholder_type_others"]
            }            
          }
        ]
      },
      {
        id: "html_response_self",
        text: "Response to Other Questions [by Self]",
        path: "mrf/assessments/reports/competency_report/html/responses_by_self",
        locals: "",
        children: [
          {
            id: "html_response_others_with_type_by_self",
            text: "Show Stakeholder Type",
            path: "mrf/assessments/reports/competency_report/html/show_stakholder_type",
            locals: {},
            links: {
              html: [],
              pdf: ["pdf_responses_with_stakholder_type_self"]
            }            
          },
          {
            id: "html_response_others_without_type_by_self",
            text: "Hide Stakeholder Type",
            path: "mrf/assessments/reports/competency_report/html/hide_stakholder_type",
            locals: {},
            links: {
              html: [],
              pdf: ["pdf_responses_without_stakholder_type_self"]
            }            
          }
        ]
      }
    ]
  },
  {
    id: "html_summary_of_360_degree_feedback",
    text: "Summary of 360 Degree Feedback",
    path: "mrf/assessments/reports/competency_report/html/page9",
    children: [],
    links: {
      html: ["html_header_summary"],
      pdf: ["pdf_page9"]
    }    
  },
  {
    id: "html_360_pagl",
    text: "360 Degree PAGL",
    path: "mrf/assessments/reports/competency_report/html/mrf_pagl",
    children: [
      {
        id: "html_360_pagl_competency_based",
        text: "360 Degree PAGL [Competency Based]",
        path: "mrf/assessments/reports/competency_report/html/mrf_pagl_competency_based",
        children: [
          {
            id: "html_development_guide_candidate",
            text: "Development Guide for the Candidate",
            path: "mrf/assessments/reports/competency_report/html/candidate_development_guide",
            locals: {}
          },
          {
            id: "html_development_guide_manager",
            text: "Guidelines for Candidates Manager",
            path: "mrf/assessments/reports/competency_report/html/candidate_manager_guidelines",
            locals: {}
          }
        ]
      },
      {
        id: "html_360_pagl_trait_based",
        text: "360 Degree PAGL [Trait Based]",
        path: "mrf/assessments/reports/competency_report/html/mrf_pagl_trait_based",
        children: [
          {
            id: "html_development_guide_candidate_trait_based",
            text: "Development Guide for the Candidate",
            path: "mrf/assessments/reports/competency_report/html/candidate_development_guide_trait_based",
            locals: {}
          },
          {
            id: "html_development_guide_manager_trait_based",
            text: "Guidelines for Candidates Manager",
            path: "mrf/assessments/reports/competency_report/html/candidate_manager_guidelines_trait_based",
            locals: {}
          }
        ]
      }
    ]
  },
  {
    id: "html_about_us",
    text: "About Us",
    path: "shared/reports/html/about_us",
    locals: {},
    links: {
      html: [],
      pdf: ["pdf_about_us"]
    }    
  },
  {
    id: "html_about_us_compact",
    text: "About Us[compact]",
    path: "shared/reports/html/about_us_compact",
    locals: {}
  },
  {
    id: "html_legal_disclaimer",
    text: "Legal Disclaimer",
    path: "shared/reports/html/legal_disclaimer",
    locals: {},
    links: {
      html: [],
      pdf: ["pdf_legal_disclaimer"]
    }    
  }
]
