:sections: [
  {
    id: "pdf_cover_page",
    text: "Cover Page",
    path: "oac/exercises/reports/competency_reports/pdf/cover_page",
    children: [
      {
        id: "pdf_candidate_details",
        text: "VDC Details",
        path: "oac/exercises/reports/competency_reports/pdf/assessment_details"  
      },
      {
        id: "pdf_completion_date",
        text: "VDC Completion Date",
        path: "oac/exercises/reports/competency_reports/pdf/completion_date"  
      }
    ]
  },
  {
    id: "pdf_table_of_contents",
    text: "Table of Contents",
    path: "oac/exercises/reports/competency_reports/pdf/table_of_contents",
  },
  {
    id: "pdf_participation",
    text: "Introduction",
    path: "oac/exercises/reports/competency_reports/pdf/participation",
  },
  {
    id: "pdf_competency_description",
    text: "Competency Description",
    path: "oac/exercises/reports/competency_reports/pdf/competency_description",
  },
  {
    id: "pdf_competency_overview",
    text: "Competency Scores",
    path: "oac/exercises/reports/competency_reports/pdf/competency_overview",
    children: [
      {
        id: "pdf_overview_legend",
        text: "Legend For Markers[With / Without Desired Range]",
        path: "oac/exercises/reports/competency_reports/pdf/competency_overview/overview",
        children: [
          {
            id: "pdf_competency_overview_legend_with_desired",
            text: "Legend With Desired Range",
            path: "oac/exercises/reports/competency_reports/pdf/competency_overview/with_desired_range",
            locals: {}
          },
          {
            id: "pdf_competency_overview_legend_without_desired",
            text: "Legend Without Desired Range",
            path: "oac/exercises/reports/competency_reports/pdf/competency_overview/without_desired_range",
            locals: {}
          }
        ]
      },
      {
        id: "pdf_overview_graph",
        text: "Graph",
        path: "oac/exercises/reports/competency_reports/pdf/competency_overview/graph_holder",
        children: [
          {
            id: "pdf_competency_overview_graph_with_desired_range",
            text: "Graph With Desired Range",
            path: "oac/exercises/reports/competency_reports/pdf/competency_overview/graph_with_desired_range",
            locals: {}
          },
          {
            id: "pdf_competency_overview_graph_without_desired_range",
            text: "Graph Without Desired Range",
            path: "oac/exercises/reports/competency_reports/pdf/competency_overview/graph_without_desired_range",
            locals: {}
          }
        ]
      }
    ]
  },
  {
    id: "pdf_one_page_competency_overview",
    text: "One Pager Competency Overview",
    path: "oac/exercises/reports/competency_reports/pdf/one_page_competency_overview",
    children: []
  },  
  {
    id: "pdf_competency_overview_tool_wise",
    text: "Toolwise Competency Overview",
    path: "oac/exercises/reports/competency_reports/pdf/competency_overview_tool_wise",
    children: []
  },
  {
    id: "pdf_toolwise_descriptions",
    text: "Tool Descriptions",
    path: "oac/exercises/reports/competency_reports/pdf/toolwise_descriptions",
    children: []
  },
  {
    id: "pdf_report_interpretation_guide",
    text: "Report Interpretation Guide",
    path: "oac/exercises/reports/competency_reports/pdf/report_interpretation_guide",
    children: []
  },
  {
    id: "pdf_top_bottom_competencies",
    text: "Top 2 and Bottom 2 Competencies",
    path: "oac/exercises/reports/competency_reports/pdf/top_bottom_competencies",
    children: []
  },
  {
    id: "pdf_scores_on_competencies",
    text: "Scores on Competencies",
    path: "oac/exercises/reports/competency_reports/pdf/scores_on_competencies",
    children: []
  },
  {
    id: "pdf_scores_on_behaviors",
    text: "Scores on Behaviors",
    path: "oac/exercises/reports/competency_reports/pdf/scores_on_behaviors",
    children: []
  },
  {
    id: "pdf_data_points_competency_wise",
    text: "Competency Wise Data Points",
    path: "oac/exercises/reports/competency_reports/pdf/data_points_competency_wise",
    children: [
      {
        id: "pdf_data_points_competency_wise_score_description",
        text: "Score Description",
        path: "oac/exercises/reports/competency_reports/pdf/competency_data_points/score_description",
        locals: {
          description: "data[:score][:description]"
        }
      },
      {
        id: "pdf_data_points_competency_wise_behaviors_measured_graph",
        text: "Behaviour Measured Graph",
        path: "oac/exercises/reports/competency_reports/pdf/competency_data_points/behaviors_measured_graph",
        locals:  {
          competency_scores: "data[:competency_scores]",
          score_buckets: "@score_buckets"
        }
      },
      {
        id: "pdf_data_points_competency_wise_strengths_improvement",
        text: "Strengths and Areas of Improvement",
        path: "oac/exercises/reports/competency_reports/pdf/competency_data_points/strengths_improvement",
        locals: {
          competency_scores: "data[:competency_scores]"
        }
      },
      {
        id: "pdf_development_guide_on_areas_of_improvement",
        text: "Development Guide Areas of Improvement",
        path: "oac/exercises/reports/competency_reports/pdf/competency_data_points/development_guide_on_areas_of_improvement",
        locals: {
          competency_scores: "competency_scores"
        }        
      },
      {
        id: "pdf_data_points_competency_wise_competency_specific_score",
        text: "Competency Wise Score",
        path: "oac/exercises/reports/competency_reports/pdf/competency_data_points/competency_specific_score",
        locals: {
          toolwise_scores: "data[:toolwise_scores]"
        },
        children: [
          {
            id: "pdf_data_points_competency_specific_scores_tools_used",
            text: "Tools Used",
            path: "oac/exercises/reports/competency_reports/pdf/competency_data_points/tools_used",
            locals: {
              toolwise_scores: "toolwise_scores"
            }
          },
          {
            id: "pdf_data_points_competency_specific_scores_toolwise_scores",
            text: "Toolwise Scores",
            path: "oac/exercises/reports/competency_reports/pdf/competency_data_points/toolwise_scores",
            locals: {
              toolwise_scores: "toolwise_scores"
            }
          }
        ]
      }
    ]
  },
   {
    id: "pdf_ultratech_idp",
    text: "Individual Development Plan",
    path: "oac/exercises/reports/competency_reports/pdf/ultratech_idp"
  },
   {
    id: "pdf_assessor_feedback_and_idp",
    text: "Individual Development Plan",
    path: "oac/exercises/reports/competency_reports/pdf/feedback_development_plan",
    children: [
      {
        id: "pdf_assessor_feedback",
        text: "Assessor Feedback",
        path: "oac/exercises/reports/competency_reports/pdf/assessor_feedback",
      },
      {
        id: "pdf_individual_development_plan",
        text: "Individidual Development Plan",
        path: "oac/exercises/reports/competency_reports/pdf/individual_development_plan",
      }
    ]
  },
  {
    id: "pdf_development_guide",
    text: "Development Guide",
    path: "oac/exercises/reports/competency_reports/pdf/development_guide",
    children: [],
    links: {
      html: [],
      pdf: []
    }
  },
  {
    id: "pdf_competencywise_assessor_feedback",
    text: "Competency Wise Assessor Feedback",
    path: "oac/exercises/reports/competency_reports/pdf/competencywise_assessor_feedback",
    children: [],
    links: {
      html: [],
      pdf: []
    }
  },  
  {
    id: "pdf_about_us_vac",
    text: "About Us[vac]",
    path: "shared/reports/pdf/about_us_vac",
    locals: {}
  }

]
