:sections: [
  {
    id: "pdf_cover_page",
    text: "Cover Page",
    path: "oac/exercises/reports/competency_reports/pdf/cover_page",
  },
  {
    id: "pdf_participation",
    text: "Participation",
    path: "oac/exercises/reports/competency_reports/pdf/participation",
  },
  {
    id: "pdf_competency_description",
    text: "Competency Description",
    path: "oac/exercises/reports/competency_reports/pdf/competency_description",
  },
  {
    id: "pdf_competency_overview",
    text: "Competency Overview",
    path: "oac/exercises/reports/competency_reports/pdf/competency_overview",
    children: [
      {
        id: "pdf_overview_legend",
        text: "Legend For Markers[With / Without Desired Range]",
        path: "oac/exercises/reports/competency_reports/pdf/competency_overview/overview",
        children: [
          {
            id: "pdf_competency_overview_legend_with_desired",
            text: "Legend With Desired Range",
            path: "oac/exercises/reports/competency_reports/pdf/competency_overview/with_desired_range",
            locals: {}
          },
          {
            id: "pdf_competency_overview_legend_without_desired",
            text: "Legend Without Desired Range",
            path: "oac/exercises/reports/competency_reports/pdf/competency_overview/without_desired_range",
            locals: {}
          }
        ]
      },
      {
        id: "pdf_overview_graph",
        text: "Graph",
        path: "oac/exercises/reports/competency_reports/pdf/competency_overview/graph_holder",
        children: [
          {
            id: "pdf_competency_overview_graph_with_desired_range",
            text: "Graph With Desired Range",
            path: "oac/exercises/reports/competency_reports/pdf/competency_overview/graph_with_desired_range",
            locals: {}
          },
          {
            id: "pdf_competency_overview_graph_without_desired_range",
            text: "Graph Without Desired Range",
            path: "oac/exercises/reports/competency_reports/pdf/competency_overview/graph_without_desired_range",
            locals: {}
          }
        ]
      }
    ]
  },
  {
    id: "pdf_one_page_competency_overview",
    text: "One Pager Competency Overview",
    path: "oac/exercises/reports/competency_reports/pdf/one_page_competency_overview",
    children: []
  },  
  {
    id: "pdf_competency_overview_tool_wise",
    text: "Toolwise Competency Overview",
    path: "oac/exercises/reports/competency_reports/pdf/competency_overview_tool_wise",
    children: []
  },
  {
    id: "pdf_toolwise_descriptions",
    text: "Toolwise Description",
    path: "oac/exercises/reports/competency_reports/pdf/toolwise_descriptions",
    children: []
  },
  {
    id: "pdf_top_bottom_competencies",
    text: "Top and Bottom Competencies",
    path: "oac/exercises/reports/competency_reports/pdf/top_bottom_competencies",
    children: []
  },
  {
    id: "pdf_data_points_competency_wise",
    text: "Data Points Competency Wise",
    path: "oac/exercises/reports/competency_reports/pdf/data_points_competency_wise",
    children: [
      {
        id: "pdf_data_points_competency_wise_score_description",
        text: "Score Description",
        path: "oac/exercises/reports/competency_reports/pdf/competency_data_points/score_description",
        locals: {
          description: "data[:score][:description]"
        }
      },
      {
        id: "pdf_data_points_competency_wise_behaviors_measured_graph",
        text: "Behaviour Measured Graph",
        path: "oac/exercises/reports/competency_reports/pdf/competency_data_points/behaviors_measured_graph",
        locals:  {
          competency_scores: "data[:competency_scores]",
          score_buckets: "@score_buckets"
        }
      },
      {
        id: "pdf_data_points_competency_wise_strengths_improvement",
        text: "Strengths and Areas of Improvement",
        path: "oac/exercises/reports/competency_reports/pdf/competency_data_points/strengths_improvement",
        locals: {
          competency_scores: "data[:competency_scores]"
        }
      },
      {
        id: "pdf_data_points_competency_wise_competency_specific_score",
        text: "Competency Wise Score",
        path: "oac/exercises/reports/competency_reports/pdf/competency_data_points/competency_specific_score",
        locals: {
          toolwise_scores: "data[:toolwise_scores]"
        },
        children: [
          {
            id: "pdf_data_points_competency_specific_scores_tools_used",
            text: "Tools Used",
            path: "oac/exercises/reports/competency_reports/pdf/competency_data_points/tools_used",
            locals: {
              toolwise_scores: "toolwise_scores"
            }
          },
          {
            id: "pdf_data_points_competency_specific_scores_toolwise_scores",
            text: "Toolwise Scores",
            path: "oac/exercises/reports/competency_reports/pdf/competency_data_points/toolwise_scores",
            locals: {
              toolwise_scores: "toolwise_scores"
            }
          }
        ]
      }
    ]
  },
   {
    id: "pdf_assessor_feedback_and_idp",
    text: "Assessor Feedback and IDP",
    path: "oac/exercises/reports/competency_reports/pdf/feedback_development_plan",
    children: [
      {
        id: "pdf_assessor_feedback",
        text: "Assessor Feedback",
        path: "oac/exercises/reports/competency_reports/pdf/assessor_feedback",
      },
      {
        id: "pdf_individual_development_plan",
        text: "Individidual Development Plan",
        path: "oac/exercises/reports/competency_reports/pdf/individual_development_plan",
      }
    ]
  },
  {
    id: "pdf_development_guide",
    text: "Development Guide",
    path: "oac/exercises/reports/competency_reports/pdf/development_guide",
    children: [],
    links: {
      html: [],
      pdf: []
    }
  },
  {
    id: "pdf_competencywise_assessor_feedback",
    text: "Competency Wise Assessor Feedback",
    path: "oac/exercises/reports/competency_reports/pdf/competencywise_assessor_feedback",
    children: [],
    links: {
      html: [],
      pdf: []
    }
  },  
  {
    id: "pdf_about_us_vac",
    text: "About Us[vac]",
    path: "shared/reports/pdf/about_us_vac",
    locals: {}
  }

]
