:sections: [
  {
    id: "pdf_cover_page",
    text: "Cover Page",
    path: "oac/exercises/reports/competency_reports/pdf/cover_page",

  },
  {
    id: "pdf_participation",
    text: "Participation",
    path: "oac/exercises/reports/competency_reports/pdf/participation",
  },
  {
    id: "pdf_competency_description",
    text: "Competency Description",
    path: "oac/exercises/reports/competency_reports/pdf/competency_description",
  },
 {
    id: "pdf_competency_overview",
    text: "Competency Overview",
    path: "oac/exercises/reports/competency_reports/pdf/competency_overview",
  },
  {
    id: "pdf_competency_overview_tool_wise",
    text: "Toolwise Competency Overview",
    path: "oac/exercises/reports/competency_reports/pdf/competency_overview_tool_wise",
    children: []
  },
  {
    id: "pdf_toolwise_descriptions",
    text: "Toolwise Description",
    path: "oac/exercises/reports/competency_reports/pdf/toolwise_descriptions",
    children: []
  },
  {
    id: "pdf_top_bottom_competencies",
    text: "Top and Bottom Competencies",
    path: "oac/exercises/reports/competency_reports/pdf/top_bottom_competencies",
    children: []
  },
  {
    id: "pdf_data_points_competency_wise",
    text: "Data Points Competency Wise",
    path: "oac/exercises/reports/competency_reports/pdf/data_points_competency_wise"

  },
  {
    id: "pdf_assessor_feedback",
    text: "Assessor Feedback",
    path: "oac/exercises/reports/competency_reports/pdf/assessor_feedback",
  },
  {
    id: "pdf_individual_development_plan",
    text: "Individidual Development Plan",
    path: "oac/exercises/reports/competency_reports/pdf/individual_development_plan",
  },

]
