:sections: [
  {
    id: "html_header",
    text: "Report Header",
    path: "oac/exercises/reports/competency_reports/html/header",
    children: [
      {
        id: "html_header_overview",
        text: "Overview",
        path: "oac/exercises/reports/competency_reports/html/header/overview",
        locals: {}
      },
      {
        id: "html_header_competencies",
        text: "Competencies",
        path: "oac/exercises/reports/competency_reports/html/header/competencies",
        locals: {}
      },
      {
        id: "html_header_tools",
        text: "Tools",
        path: "oac/exercises/reports/competency_reports/html/header/tools",
        locals: {}
      },
      {
        id: "html_header_remarks",
        text: "Remarks",
        path: "oac/exercises/reports/competency_reports/html/header/remarks",
        locals: {}
      }
    ]
  },
  {
    id: "html_partners",
    text: "Partners",
    path: "oac/exercises/reports/competency_reports/html/partners",
    children: []
  },
  {
    id: "html_cover_page",
    text: "Cover Page",
    path: "oac/exercises/reports/competency_reports/html/cover_page",
    children: [
      {
        id: "html_cover_page_aggregate_score",
        text: "Aggregate Score",
        path: "oac/exercises/reports/competency_reports/html/cover_page/aggregate_score",
        locals: {}
      },
      {
        id: "html_cover_page_color_band",
        text: "Color Band",
        path: "oac/exercises/reports/competency_reports/html/cover_page/color_band",
        locals: {}
      }
    ]
  },
  {
    id: "html_participation",
    text: "Particiaption",
    path: "oac/exercises/reports/competency_reports/html/participation",
    children: []
  },
  {
    id: "html_competency_description",
    text: "Competency Description",
    path: "oac/exercises/reports/competency_reports/html/competency_description",
    children: []
  },
  {
    id: "html_competency_overview",
    text: "Competency Overview",
    path: "oac/exercises/reports/competency_reports/html/competency_overview",
    children: [
      {
        id: "html_competency_overview_legend",
        text: "Legend For Markers",
        path: "oac/exercises/reports/competency_reports/html/competency_overview_legend_holder",
        children: [
          {
            id: "html_competency_overview_legend_with_desired",
            text: "Legend With Desired Range",
            path: "oac/exercises/reports/competency_reports/html/competency_overview_legend_with_desired_range",
            locals: {}
          },
          {
            id: "html_competency_overview_legend_without_desired",
            text: "Legend Without Desired Range",
            path: "oac/exercises/reports/competency_reports/html/competency_overview_legend_without_desired_range",
            locals: {}
          }
        ]
      },
      {
        id: "html_competency_overview_graph",
        text: "Graph",
        path: "oac/exercises/reports/competency_reports/html/competency_overview_graph_holder",
        children: [
          {
            id: "html_competency_overview_graph_with_desired_range",
            text: "Graph With Desired Range",
            path: "oac/exercises/reports/competency_reports/html/competency_overview_graph_holder_with_desired_range",
            locals: {}
          },
          {
            id: "html_competency_overview_graph_without_desired_range",
            text: "Graph Without Desired Range",
            path: "oac/exercises/reports/competency_reports/html/competency_overview_graph_holder_without_desired_range",
            locals: {}
          }
        ]
      }
    ]
  },
  {
    id: "html_competency_overview_tool_wise",
    text: "Toolwise Competency Overview",
    path: "oac/exercises/reports/competency_reports/html/competency_overview_tool_wise",
    children: []
  },
  {
    id: "html_toolwise_descriptions",
    text: "Toolwise Description",
    path: "oac/exercises/reports/competency_reports/html/toolwise_descriptions",
    children: []
  },
  {
    id: "html_top_bottom_competencies",
    text: "Top and Bottom Competencies",
    path: "oac/exercises/reports/competency_reports/html/top_bottom_competencies",
    children: []
  },
  {
    id: "html_data_points_competency_wise",
    text: "Data Points Competency Wise",
    path: "oac/exercises/reports/competency_reports/html/data_points_competency_wise",
    children: []
  },
  {
    id: "html_assessor_feedback",
    text: "Assessor Feedback",
    path: "oac/exercises/reports/competency_reports/html/assessor_feedback",
    children: []
  },
  {
    id: "html_individual_development_plan",
    text: "Individidual Development Plan",
    path: "oac/exercises/reports/competency_reports/html/individual_development_plan",
    children: []
  }
]
