:sections: [
  {
    id: "html_header",
    text: "Report Header",
    path: "oac/exercises/reports/competency_reports/html/header",
    children: [
      {
        id: "html_header_menu",
        text: "Menu Items",
        path: "oac/exercises/reports/competency_reports/html/header/menu",
        children: [
          {
            id: "html_header_overview",
            text: "Overview",
            path: "oac/exercises/reports/competency_reports/html/header/overview",
            locals: {}        
          },
          {
            id: "html_header_competencies",
            text: "Competencies",
            path: "oac/exercises/reports/competency_reports/html/header/competencies",
            locals: {}   
          },
          {
            id: "html_header_tools",
            text: "Tools",
            path: "oac/exercises/reports/competency_reports/html/header/tools",
            locals: {}    
          },
          {
            id: "html_header_remarks",
            text: "Remarks",
            path: "oac/exercises/reports/competency_reports/html/header/remarks",
            locals: {}    
          }
        ]
      },
      {
        id: "html_download_pdf_link",
        text: "Download PDF Link",
        path: "oac/exercises/reports/competency_reports/html/header/download_pdf_link",
        locals: {}
      }
    ]
  },
  {
    id: "html_partners",
    text: "Partners",
    path: "oac/exercises/reports/competency_reports/html/partners",
    children: []
  },
  {
    id: "html_cover_page",
    text: "Cover Page",
    path: "oac/exercises/reports/competency_reports/html/cover_page",
    children: [
      {
        id: "html_cover_page_name_and_details",
        text: "Name and Completion Date",
        path: "oac/exercises/reports/competency_reports/html/cover_page/details",
        locals: {},
        links: {
          html: ["html_header_overview"],
          pdf: ["pdf_candidate_details","pdf_completion_date"]
        }   
      },
      {
        id: "html_cover_page_aggregate_score_bands",
        text: "Score, Numberical and Color Bands",
        path: "oac/exercises/reports/competency_reports/html/cover_page/score_color_bands",
        locals: {},
        children: [
          {
            id: "html_cover_page_aggregate_score",
            text: "Aggregate Score",
            path: "oac/exercises/reports/competency_reports/html/cover_page/aggregate_score",
            locals: {
              aggregate_score_bucket: "aggregate_score_bucket"
            }              
          },
          {
            id: "html_cover_page_color_band",
            text: "Color Band",
            path: "oac/exercises/reports/competency_reports/html/cover_page/color_band",
            locals: {
              aggregate_score_color: "aggregate_score_color",
              aggregate_score_rating: "aggregate_score_rating"
            }               
          }
        ]
      }
    ],
    links: {
      html: [],
      pdf: ["pdf_cover_page"]
    }    
  },
  {
    id: "html_participation",
    text: "Introduction",
    path: "oac/exercises/reports/competency_reports/html/participation",
    children: [],
    links: {
      html: [],
      pdf: ["pdf_participation"]
    }    
  },
  {
    id: "html_competency_description",
    text: "Competency Description",
    path: "oac/exercises/reports/competency_reports/html/competency_description",
    children: [],
    links: {
      html: [],
      pdf: ["pdf_competency_description"]
    } 
  },
  {
    id: "html_competency_overview",
    text: "Competency Scores",
    path: "oac/exercises/reports/competency_reports/html/competency_overview",
    children: [
      {
        id: "html_competency_overview_legend",
        text: "Legend For Markers[With / Without Desired Range]",
        path: "oac/exercises/reports/competency_reports/html/competency_overview/overview",
        children: [
          {
            id: "html_competency_overview_legend_with_desired",
            text: "Legend With Desired Range",
            path: "oac/exercises/reports/competency_reports/html/competency_overview/with_desired_range",
            locals: {},
            links: {
              html: ["html_header_competencies",],
              pdf: ["pdf_competency_overview_legend_with_desired"]
            }            
          },
          {
            id: "html_competency_overview_legend_without_desired",
            text: "Legend Without Desired Range",
            path: "oac/exercises/reports/competency_reports/html/competency_overview/without_desired_range",
            locals: {},
            links: {
              html: ["html_header_competencies",],
              pdf: ["pdf_competency_overview_legend_without_desired"]
            }            
          }
        ]
      },
      {
        id: "html_competency_overview_graph",
        text: "Graph",
        path: "oac/exercises/reports/competency_reports/html/competency_overview/graph_holder",
        children: [
          {
            id: "html_competency_overview_graph_with_desired_range",
            text: "Graph With Desired Range",
            path: "oac/exercises/reports/competency_reports/html/competency_overview/graph_with_desired_range",
            locals: {},
            links: {
              html: [],
              pdf: ["pdf_competency_overview_graph_with_desired_range"]
            }            
          },
          {
            id: "html_competency_overview_graph_without_desired_range",
            text: "Graph Without Desired Range",
            path: "oac/exercises/reports/competency_reports/html/competency_overview/graph_without_desired_range",
            locals: {},
            links: {
              html: [],
              pdf: ["pdf_competency_overview_graph_without_desired_range"]
            }            
          }
        ]
      }
    ]
  },
  {
    id: "html_competency_overview_tool_wise",
    text: "Toolwise Competency Overview",
    path: "oac/exercises/reports/competency_reports/html/competency_overview_tool_wise",
    children: [],
    links: {
      html: ["html_header_tools"],
      pdf: ["pdf_competency_overview_tool_wise"]
    }    
  },
  {
    id: "html_toolwise_descriptions",
    text: "Tool Descriptions",
    path: "oac/exercises/reports/competency_reports/html/toolwise_descriptions",
    children: [],
    links: {
      html: [],
      pdf: ["pdf_toolwise_descriptions"]
    }    
  },
  {
    id: "html_top_bottom_competencies",
    text: "Top 2 and Bottom 2 Competencies",
    path: "oac/exercises/reports/competency_reports/html/top_bottom_competencies",
    children: [],
    links: {
      html: [],
      pdf: ["pdf_top_bottom_competencies"]
    }    
  },
  {
    id: "html_data_points_competency_wise",
    text: "Competency Wise Data Points",
    path: "oac/exercises/reports/competency_reports/html/data_points_competency_wise",
    children: [
      {
        id: "html_data_points_competency_wise_score_description",
        text: "Score Description",
        path: "oac/exercises/reports/competency_reports/html/competency_data_points/score_description",
        locals: {
          description: "data[:score][:description]"
        },
        links: {
          html: [],
          pdf: ["pdf_data_points_competency_wise_score_description"]
        }        
      },
      {
        id: "html_data_points_competency_wise_behaviors_measured_graph",
        text: "Behaviour Measured Graph",
        path: "oac/exercises/reports/competency_reports/html/competency_data_points/behaviors_measured_graph",
        locals: {
          competency_scores: "data[:competency_scores]",
          score_buckets: "@score_buckets"
        },
        links: {
          html: [],
          pdf: ["pdf_data_points_competency_wise_behaviors_measured_graph"]
        }        
      },
      {
        id: "html_data_points_competency_wise_strengths_improvement",
        text: "Strengths and Areas of Improvement",
        path: "oac/exercises/reports/competency_reports/html/competency_data_points/strengths_improvement",
        locals: {
          competency_scores: "data[:competency_scores]"
        },
        links: {
          html: [],
          pdf: ["pdf_data_points_competency_wise_strengths_improvement"]
        }        
      },
      {
        id: "html_guides_on_areas_of_improvement",
        text: "Development Guide Areas of Improvement",
        path: "oac/exercises/reports/competency_reports/html/competency_data_points/development_guide_on_areas_of_improvement",
        locals: {
          competency_scores: "competency_scores"
        },
        links: {
          html: [],
          pdf: ["pdf_development_guide_on_areas_of_improvement"]
        }        
      },
      {
        id: "html_data_points_competency_wise_competency_specific_score",
        text: "Competency Wise Score",
        path: "oac/exercises/reports/competency_reports/html/competency_data_points/competency_specific_score",
        locals: {
          toolwise_scores: "data[:toolwise_scores]"
        },
        children: [
          {
            id: "html_data_points_competency_specific_scores_tools_used",
            text: "Tools Used",
            path: "oac/exercises/reports/competency_reports/html/competency_data_points/tools_used",
            locals: {
              toolwise_scores: "toolwise_scores"
            },
            links: {
              html: [],
              pdf: ["pdf_data_points_competency_specific_scores_tools_used"]
            }
          },
          {
            id: "html_data_points_competency_specific_scores_toolwise_scores",
            text: "Toolwise Scores",
            path: "oac/exercises/reports/competency_reports/html/competency_data_points/toolwise_scores",
            locals: {
              toolwise_scores: "toolwise_scores"
            },
            links: {
              html: [],
              pdf: ["pdf_data_points_competency_specific_scores_toolwise_scores"]
            }
          }
        ]
      },
      {
        id: "html_competency_wise_assessor_feedback",
        text: "Assessor Feedback",
        path: "oac/exercises/reports/competency_reports/html/competency_data_points/assessor_feedback",
        locals: {
          assessor_feedback: "assessor_feedback"
        },
        links: {
          html: [],
          pdf: ["pdf_competency_wise_assessor_feedback"]
        }
      }
    ]
  },
  {
    id: "html_assessor_feedback",
    text: "Assessor Feedback",
    path: "oac/exercises/reports/competency_reports/html/assessor_feedback",
    children: [],
    links: {
      html: ["html_header_remarks"],
      pdf: ["pdf_assessor_feedback"]
    }
  },
  {
    id: "html_development_guide",
    text: "Development Guide",
    path: "oac/exercises/reports/competency_reports/html/development_guide",
    children: [],
    links: {
      html: [],
      pdf: ["pdf_development_guide"]
    }
  },
  {
    id: "html_individual_development_plan",
    text: "Individidual Development Plan",
    path: "oac/exercises/reports/competency_reports/html/individual_development_plan",
    children: [],
    links: {
      html: [],
      pdf: ["pdf_individual_development_plan"]
    }
  },
  {
    id: "html_report_interpretation_guide",
    text: "Report Interpretation Guide",
    path: "oac/exercises/reports/competency_reports/html/report_interpretation_guide",
    children: [],
    links: {
      html: [],
      pdf: ["pdf_report_interpretation_guide"]
    }
  },
  {
    id: "html_scores_on_competencies",
    text: "Scores on Competencies",
    path: "oac/exercises/reports/competency_reports/html/scores_on_competencies",
    children: [],
    links: {
      html: [],
      pdf: ["pdf_scores_on_competencies"]
    }
  },
  {
    id: "html_scores_on_behaviors",
    text: "Scores on Behaviors",
    path: "oac/exercises/reports/competency_reports/html/scores_on_behaviors",
    children: [],
    links: {
      html: [],
      pdf: ["pdf_scores_on_behaviors"]
    }
  },
  {
    id: "html_ultratech_idp",
    text: "Individual Development Plan",
    path: "oac/exercises/reports/competency_reports/html/ultratech_idp",
    children: [],
    links: {
      html: [],
      pdf: ["pdf_ultratech_idp"]
    }
  },
  {
    id: "html_competencywise_assessor_comment",
    text: "Competency Wise Assessor Comments",
    path: "oac/exercises/reports/competency_reports/html/competencywise_assessor_comment",
    children: [],
    links: {
      html: [],
      pdf: ["pdf_competencywise_assessor_feedback"]
    }
  },    
  {
    id: "html_about_us_vac",
    text: "About Us[vac]",
    path: "shared/reports/html/about_us_vac",
    locals: {}
  }
]
