:sections: [
  {
    id: "pdf_cover_page_compact",
    text: "Cover Page [COMPACT]",
    path: "assessment_reports/competency_report/pdf/cover_page_compact",
    children: [
      {
        id: "pdf_cover_page_compact_aggregate_numerical_score",
        text: "Aggregate Numerical Score [Score]",
        path: "assessment_reports/competency_report/pdf/aggregate_numerical_score_compact",
        locals: {}
      },      
      {
        id: "pdf_cover_page_compact_aggregate_score",
        text: "Aggregate Score",
        path: "assessment_reports/competency_report/pdf/aggregate_score_compact",
        locals: {}
      },
      {
        id: "pdf_cover_page_compact_color_band",
        text: "Color Band",
        path: "assessment_reports/competency_report/pdf/color_band_compact",
        locals: {}
      },
      {
        id: "pdf_cover_page_compact_overview_competencies_measured",
        text: "Overview Of Competencies/Value Measured",
        path: "assessment_reports/competency_report/pdf/competency_scores_overview/main_compact",
        children: [
          {
            id: "pdf_competency_scores_overview_favourable_within_desired_range_compact",
            text: "Scale [Show Favourable within Desired Range]",
            path: "assessment_reports/competency_report/pdf/competency_scores_overview/favourable_within_desired_range",
            locals: {
              competency_scores: "competency_scores"
            },
            children: [
              {
                id: "pdf_favourable_within_desired_range_show_desired_range_compact",
                text: "Show Desired Range",
                path: "assessment_reports/competency_report/pdf/competency_scores_overview/show_desired_range",
                locals: {
                  width: "width",
                  offset: "offset"
                }
              },
              {
                id: "pdf_favourable_within_desired_range_hide_desired_range_compact",
                text: "Hide Desired Range",
                path: "assessment_reports/competency_report/pdf/competency_scores_overview/hide_desired_range",
                locals: {
                  width: "width",
                  offset: "offset"
                }
              }
            ]
          },
          {
            id: "pdf_competency_scores_overview_favourable_above_desired_range_compact",
            text: "Scale [Show Favourable above Desired Range]",
            path: "assessment_reports/competency_report/pdf/competency_scores_overview/favourable_above_desired_range",
            locals: {
              competency_scores: "competency_scores"
            },
            children: [
              {
                id: "pdf_favourable_above_desired_range_show_desired_range_compact",
                text: "Show Desired Range",
                path: "assessment_reports/competency_report/pdf/competency_scores_overview/show_desired_range",
                locals: {
                  width: "width",
                  offset: "offset"
                }
              },
              {
                id: "pdf_favourable_above_desired_range_hide_desired_range_compact",
                text: "Hide Desired Range",
                path: "assessment_reports/competency_report/pdf/competency_scores_overview/hide_desired_range",
                locals: {
                  width: "width",
                  offset: "offset"
                }
              }
            ]
          }
        ]
      }
    ]
  },
  {
    id: "pdf_cover_page",
    text: "Cover Page [Details]",
    path: "assessment_reports/competency_report/pdf/cover_page",
    children: [
      {
        id: "pdf_enable_aggregate_score",
        text: "Aggregate Score | Color Band | Functional Trait",
        path: "assessment_reports/competency_report/pdf/enable_aggregate_competency_score",
        children: [
          {
            id: "pdf_aggregate_score_text",
            text: "Aggregate Score",
            path: "assessment_reports/competency_report/pdf/aggregate_score_text",
            children: [],
            locals: {},
          },
          {
            id: "pdf_color_band",
            text: "Color Band",
            path: "assessment_reports/competency_report/pdf/color_band",
            children: [],
            locals: {},
          },
          {
            id: "pdf_functional_trait_legend",
            text: "Functional Trait Legend",
            path: "assessment_reports/competency_report/pdf/functional_trait_legend",
            children: [
              {
                id: "pdf_with_functional_legend",
                text: "Functional Traits Legend Present",
                path: "assessment_reports/competency_report/pdf/functional_trait_legend_present",
                children: [],
                locals: {}
              },
              {
                id: "pdf_without_functional_legend",
                text: "Functional Traits Legend Not Present",
                path: "assessment_reports/competency_report/pdf/functional_trait_legend_absent",
                children: [],
                locals: {}
              }
            ]
          }
        ]
      },
      {
        id: "pdf_assessment_details",
        text: "Assessment Details [Name and Completion Date]",
        path: "assessment_reports/competency_report/pdf/assessment_details",
        locals: {}
      }
    ]
  },
  {
    id: "pdf_competency_report_guideline",
    text: "Guidelines to interpret the report",
    path: "assessment_reports/competency_report/pdf/competency_report_guideline",
    children: []
  },
  {
    id: "pdf_competency_scores_overview",
    text: "Overview of Competencies Measured",
    path: "assessment_reports/competency_report/pdf/competency_scores_overview/main",
    children: [
      {
        id: "pdf_competency_scores_overview_favourable_within_desired_range",
        text: "Scale [Show Favourable within Desired Range]",
        path: "assessment_reports/competency_report/pdf/competency_scores_overview/favourable_within_desired_range",
        locals: {
          competency_scores: "competency_scores"
        },
        children: [
          {
            id: "pdf_favourable_within_desired_range_show_desired_range",
            text: "Show Desired Range",
            path: "assessment_reports/competency_report/pdf/competency_scores_overview/show_desired_range",
            locals: {
              width: "width",
              offset: "offset"
            }
          },
          {
            id: "pdf_favourable_within_desired_range_hide_desired_range",
            text: "Hide Desired Range",
            path: "assessment_reports/competency_report/pdf/competency_scores_overview/hide_desired_range",
            locals: {
              width: "width",
              offset: "offset"
            }
          }
        ]
      },
      {
        id: "pdf_competency_scores_overview_favourable_above_desired_range",
        text: "Scale [Show Favourable above Desired Range]",
        path: "assessment_reports/competency_report/pdf/competency_scores_overview/favourable_above_desired_range",
        locals: {
          competency_scores: "competency_scores"
        },
        children: [
          {
            id: "pdf_favourable_above_desired_range_show_desired_range",
            text: "Show Desired Range",
            path: "assessment_reports/competency_report/pdf/competency_scores_overview/show_desired_range",
            locals: {
              width: "width",
              offset: "offset"
            }
          },
          {
            id: "pdf_favourable_above_desired_range_hide_desired_range",
            text: "Hide Desired Range",
            path: "assessment_reports/competency_report/pdf/competency_scores_overview/hide_desired_range",
            locals: {
              width: "width",
              offset: "offset"
            }
          }
        ]
      }
    ]
  },
  {
    id: "pdf_aptitude_score",
    text: "Score for Aptitude",
    path: "assessment_reports/competency_report/pdf/aptitude_score",
    children: []
  },
  {
    id: "pdf_aptitude_score_explanation",
    text: "Explanation of CoCubes Score",
    path: "assessment_reports/competency_report/pdf/explanation_of_cocubes_score",
    children: []
  },
  {
    id: "pdf_score_scale",
    text: "Explainations for Jombay Scores [Score Scale]",
    path: "assessment_reports/score_scale",
    children: []
  },
  {
    id: "pdf_explanation_scores",
    text: "Explainations for Jombay Scores",
    path: "assessment_reports/competency_report/pdf/explanation_scores",
    children: []
  },
  {
    id: "pdf_competencies_values_measured",
    text: "Competencies Measured",
    path: "assessment_reports/competency_report/pdf/compentencies_values_measured",
    children: 
    [
      {
        id: "pdf_custom_factor_block",
        text: "Custom Competency Block [Scores above range are shown as favourable]",
        path: "assessment_reports/competency_report/pdf/custom_factor_block",
        locals: {
          step_competency_scores: "step_competency_scores"
        }
      },
      {
        id: "pdf_generic_factor_block",
        text: "Generic Competency Block [Scores outside range are not favourable]",
        path: "assessment_reports/competency_report/pdf/generic_factor_block",
        locals: {
          step_competency_scores: "step_competency_scores"
        }
      }
    ]
  },
  {
    id: "pdf_factor_scores_unders_competencies",
    text: "Scores of factors measured under different competencies",
    path: "assessment_reports/competency_report/pdf/factor_scores_under_competencies",
    children: [
      {
        id: "pdf_generic_competency_with_consistency",
        text: "Generic Factor Block [Outside Range is not Favourable] With Consistency",
        path: "assessment_reports/competency_report/pdf/generic_competency_consistency_enabled",
        locals: {}
      },
      {
        id: "pdf_generic_competency_without_consistency",
        text: "Generic Factor Block [Outside Range is not Favourable] Without Consistency",
        path: "assessment_reports/competency_report/pdf/generic_competency_consistency_disabled",
        locals: {}
      },
      {
        id: "pdf_custom_competency_with_consistency",
        text: "Custom Factor Block [Above range is Favourable] With Consistency",
        path: "assessment_reports/competency_report/pdf/custom_competency_consistency_enabled",
        locals: {}
      },
      {
        id: "pdf_custom_competency_without_consistency",
        text: "Custom Factor Block [Above range is Favourable] Without Consistency",
        path: "assessment_reports/competency_report/pdf/custom_competency_consistency_disabled",
        locals: {}
      }
    ]
  },
  {
    id: "pdf_functional_overview_sections",
    text: "Overview of scores of Subjective/Objective questions",
    path: "assessment_reports/functional_report/pdf/functional_overview_section",
    children: []
  },
  {
    id: "pdf_objective_questions",
    text: "Objective Questions",
    path: "assessment_reports/functional_report/pdf/objective_questions",
    children: []
  },
  {
    id: "pdf_subjective_questions",
    text: "Subjective Questions",
    path: "assessment_reports/functional_report/pdf/subjective_questions",
    children: []
  },
  {
    id: "pdf_miscellaneous_factors",
    text: "Miscellaneous Factors",
    path: "assessment_reports/competency_report/pdf/miscellaneous_factors",
    children: []
  },
  {
    id: "pdf_interview_questions_for_candidate",
    text: "Interview Questions[BASED ON CANIDATE TYPE]",
    path: "assessment_reports/competency_report/pdf/interview_guide_candidate",
    locals: {}
  },
  {
    id: "pdf_interview_questions_for_candidate_stage_based",
    text: "Interview Questions",
    path: "assessment_reports/competency_report/pdf/interview_guide",
    locals: {}
  },
  {
    id: "pdf_development_interview_guide_candidate",
    text: "Development Guide for Candidate[BASED ON CANDIDATE TYPE]",
    path: "assessment_reports/competency_report/pdf/development_interview_guide_candidate",
    children: []
  },
  {
    id: "pdf_development_interview_guide_candidate_stage_based",
    text: "Development Guide for Candidate",
    path: "assessment_reports/competency_report/pdf/development_guide_candidate",
    children: []
  },
  {
    id: "pdf_development_interview_guide_manager",
    text: "Guidelines for Assessment takers manager[BASED ON CANIDATE TYPE]",
    path: "assessment_reports/competency_report/pdf/development_interview_guide_manager",
    children: []
  },
  {
    id: "pdf_development_interview_guide_manager_stage_based",
    text: "Guidelines for Assessment takers manager",
    path: "assessment_reports/competency_report/pdf/development_guide_manager",
    children: []
  },
  {
    id: "pdf_about_us",
    text: "About Us",
    path: "shared/reports/pdf/about_us",
    locals: {}
  },
  {
    id: "pdf_legal_disclaimer",
    text: "Legal Disclaimer",
    path: "shared/reports/pdf/legal_disclaimer",
    locals: {}
  }
]