:sections: [
  {
    id: "pdf_cover_page",
    text: "Cover Page [Details]",
    path: "assessment_reports/competency_report/pdf/cover_page",
    children: [
      {
        id: "pdf_enable_aggregate_score",
        text: "Aggregate Score | Color Band | Functional Trait",
        path: "assessment_reports/competency_report/pdf/enable_aggregate_competency_score",
        children: [
          {
            id: "pdf_aggregate_score_text",
            text: "Aggregate Score",
            path: "assessment_reports/competency_report/pdf/aggregate_score_text",
            children: [],
            locals: {},
          },
          {
            id: "pdf_color_band",
            text: "Color Band",
            path: "assessment_reports/competency_report/pdf/color_band",
            children: [],
            locals: {},
          }
        ]
      },
      {
        id: "pdf_assessment_details",
        text: "Assessment Details [Name and Completion Date]",
        path: "assessment_reports/competency_report/pdf/assessment_details",
        locals: {}
      }
    ]
  },
  {
    id: "pdf_competency_scores_overview",
    text: "Overview of Competencies Measured",
    path: "assessment_reports/competency_report/pdf/competency_scores_overview/main",
    children: [
      {
        id: "pdf_competency_scores_overview_title_with_expected_score",
        text: "Title With Expected Score",
        path: "assessment_reports/competency_report/pdf/competency_scores_overview/title_with_expected_score",
        locals: {}
      },
      {
        id: "pdf_competency_scores_overview_title_without_expected_score",
        text: "Title Without Expected Score",
        path: "assessment_reports/competency_report/pdf/competency_scores_overview/title_without_expected_score",
        locals: {}
      },
      {
        id: "pdf_competency_scores_overview_favourable_within_desired_range",
        text: "Scale [Show Favourable within Desired Range]",
        path: "assessment_reports/competency_report/pdf/competency_scores_overview/favourable_within_desired_range",
        locals: {
          competency_scores: "competency_scores"
        },
        children: [
          {
            id: "pdf_favourable_within_desired_range_show_desired_range",
            text: "Show Desired Range",
            path: "assessment_reports/competency_report/pdf/competency_scores_overview/show_desired_range",
            locals: {
              width: "width",
              offset: "offset"
            }
          },
          {
            id: "pdf_favourable_within_desired_range_hide_desired_range",
            text: "Hide Desired Range",
            path: "assessment_reports/competency_report/pdf/competency_scores_overview/hide_desired_range",
            locals: {
              width: "width",
              offset: "offset"
            }
          }
        ]
      }
    ]
  },
  {
    id: "pdf_competencies_values_measured",
    text: "Competencies Measured [Hexagonal Block]",
    path: "assessment_reports/competency_report/pdf/compentencies_values_measured",
    children: 
    [
      {
        id: "pdf_generic_factor_block",
        text: "Generic Competency Block [Scores outside range are not favourable]",
        path: "assessment_reports/competency_report/pdf/sjt_factor_block",
        locals: {
          step_competency_scores: "step_competency_scores"
        }
      }
    ]
  },
  {
    id: "html_sjt",
    text: "Scores of Competencies/Values measured",
    path: "assessment_reports/sjt/pdf/sjt_competency_block",
    locals: {}
  },
  {
    id: "pdf_about_us",
    text: "About Us",
    path: "shared/reports/pdf/about_us",
    locals: {}
  },
  {
    id: "pdf_legal_disclaimer",
    text: "Legal Disclaimer",
    path: "shared/reports/pdf/legal_disclaimer",
    locals: {}
  }
]
