:sections: [
  {
    id: "html_header",
    text: "Report Header",
    path: "shared/reports/candidate_report_main_header",
    children: [
      {
        id: "html_header_menu",
        text: "Menu",
        path: "shared/reports/suitability/header/menu",
        children: [
          {
            id: "html_header_overview",
            text: "Overview",
            path: "shared/reports/suitability/header/overview"
          },
          {
            id: "html_header_traits",
            text: "Traits",
            path: "shared/reports/suitability/header/traits_measured"
          },
          {
            id: "html_header_trait_scores",
            text: "Traits Scores",
            path: "shared/reports/suitability/header/scores_of_traits_measured"
          }
        ]
      },
      {
        id: "html_header_download_pdf_link",
        text: "Download PDF Link",
        path: "shared/reports/suitability/header/download_pdf_link",
      }
    ]
  },
  {
    id: "html_cover_page",
    text: "Cover Page [Details]",
    path: "assessment_reports/competency_report/html/cover_page",
    children: [
      {
        id: "html_aggregate_competency_score",
        text: "Aggregate Competency Scores",
        path: "assessment_reports/competency_report/html/aggregate_competency_score",
        children: [
          {
            id: "html_aggregate_score_bucket",
            text: "Aggregate Competency Score[Bucket]",
            path: "assessment_reports/competency_report/html/aggregate_score_bucket",
            locals: {},
            children: []
          },
          {
            id: "html_color_band",
            text: "Color Band",
            path: "assessment_reports/competency_report/html/competency_score_rating_on_overall_score",
            locals: {},
            children: []
          },
        ]
      },
      {
        id: "html_assessment_details",
        text: "Assessment[Name and Completion Date]",
        path: "assessment_reports/competency_report/html/assessment_details",
        locals: {},
        children: []
      }
    ]
  },
  {
    id: "html_competency_scores_overview",
    text: "Overview of Competencies Measured",
    path: "assessment_reports/competency_report/html/competency_scores_overview/main",
    locals: {},
    children: [
      {
        id: "html_competency_scores_overview_legend",
        text: "Competency Scores Overview Legend",
        path: "assessment_reports/competency_report/html/competency_scores_overview/legend",
        locals: {},
        children: [
          {
            id: "html_competency_scores_overview_title",
            text: "Competency Scores Overview Title",
            path: "assessment_reports/competency_report/html/competency_scores_overview/competency_scores_overview_title",
            locals: {}
          },
          {
            id: "html_competency_scores_overview_generic_legend",
            text: "Generic Legend",
            path: "assessment_reports/competency_report/html/competency_scores_overview/custom_legend",
            locals: {}
          }
        ]
      },
      {
        id: "html_show_generic_scale",
        text: "Scale [Outside Range is Not Favourable]",
        path: "assessment_reports/competency_report/html/competency_scores_overview/favourable_within_desired_range",
        locals: {
          competency_scores: "competency_scores"
        },
        children: [
          {
            id: "html_competency_scores_overview_generic_show_desired_ranges",
            text: "Show Desired Ranges",
            path: "assessment_reports/competency_report/html/competency_scores_overview/show_desired_range",
            locals: {
              width: "width",
              offset: "offset"
            }
          },
          {
            id: "html_competency_scores_overview_generic_hide_desired_ranges",
            text: "Hide Desired Ranges",
            path: "assessment_reports/competency_report/html/competency_scores_overview/hide_desired_range",
            locals: {
              width: "width",
              offset: "offset"
            }
          }
        ]
      }
    ]
  },
  {
    id: "html_competencies_values_measured",
    text: "Competencies Measured",
    path: "assessment_reports/competency_report/html/comptencies_values_measured",
    children: [
      {
        id: "html_generic_factor_block",
        text: "SJT Competency Block[Hexagonal Graphs]",
        path: "assessment_reports/competency_report/html/sjt_hexagon_block",
        locals: {
          step_competency_scores: "step_competency_scores"
        }
      }
    ]
  },
  {
    id: "html_sjt",
    text: "Scores of Competencies/Values measured",
    path: "assessment_reports/sjt/html/sjt_competency_block",
    locals: {}
  },
  {
    id: "html_about_us",
    text: "About Us",
    path: "shared/reports/html/about_us",
    locals: {}
  },
  {
    id: "html_legal_disclaimer",
    text: "Legal Disclaimer",
    path: "shared/reports/html/legal_disclaimer",
    locals: {}
  }
]