:sections: [
  {
    id: "html_header",
    text: "Report Header",
    path: "shared/reports/candidate_report_main_header",
    children: [
      {
        id: "html_header_menu",
        text: "Menu",
        path: "shared/reports/suitability/header/menu",
        children: [
          {
            id: "html_header_overview",
            text: "Overview",
            path: "shared/reports/suitability/header/overview"
          },
          {
            id: "html_header_traits",
            text: "Traits",
            path: "shared/reports/suitability/header/traits_measured"
          },
          {
            id: "html_header_trait_scores",
            text: "Traits Scores",
            path: "shared/reports/suitability/header/scores_of_traits_measured"
          },
          {
            id: "html_header_development_guide_for_assessment_taker",
            text: "Development Guide for Assessment Taker",
            path: "shared/reports/suitability/header/development_guide_for_assessment_taker"
          },
          {
            id: "html_header_development_guide_for_manager",
            text: "Development Guide for Manager",
            path: "shared/reports/suitability/header/development_guide_for_manager"
          }
        ]
      },
      {
        id: "html_header_download_pdf_link",
        text: "Download PDF Link",
        path: "shared/reports/suitability/header/download_pdf_link",
      },
      {
        id: "html_header_brand_partner_logo",
        text: "Brand Partner Logo",
        path: "shared/reports/suitability/header/brand_partner_logo",
      }
    ]
  },
  {
    id: "html_cover_page",
    text: "Cover Page",
    path: "assessment_reports/competency_report/html/cover_page",
    children: [
      {
        id: "html_feedback_header",
        text: "Feedback Header",
        path: "shared/reports/feedback_header",
        locals: {},
        children: []
      },
      {
        id: "html_aggregate_competency_score",
        text: "Aggregate Competency Scores",
        path: "assessment_reports/competency_report/html/aggregate_competency_score",
        children: [
          {
            id: "html_aggregate_score_bucket",
            text: "Aggregate Competency Score[Bucket]",
            path: "assessment_reports/competency_report/html/aggregate_score_bucket",
            locals: {},
            children: []
          },
          {
            id: "html_color_band",
            text: "Color Band",
            path: "assessment_reports/competency_report/html/competency_score_rating_on_overall_score",
            locals: {},
            children: []
          },
          {
            id: "html_functional_items_legend",
            text: "Functional Items Legend",
            path: "assessment_reports/competency_report/html/functional_items_legend",
            children: [
              {
                id: "html_include_functional_legend",
                text: "Include Functional Items Legend",
                path: "assessment_reports/competency_report/html/include_functional_legend",
                locals: {}
              },
              {
                id: "html_exculde_functional_legend",
                text: "Exclude Functional Items Legend",
                path: "assessment_reports/competency_report/html/exclude_functional_legend",
                locals: {}
              }
            ]
          }
        ]
      },
      {
        id: "html_assessment_details",
        text: "Assessment[Name and Completion Date]",
        path: "assessment_reports/competency_report/html/assessment_details",
        locals: {},
        children: []
      }
    ]
  },
  {
    id: "html_competency_interpretation_guide",
    text: "Competency Interpretation Guidelines",
    path: "assessment_reports/competency_report/html/competency_interpretation_guide",
    children: []
  },
  {
    id: "html_competency_scores_overview",
    text: "Competency Scores Overview",
    path: "assessment_reports/competency_report/html/competency_scores_overview/main",
    locals: {},
    children: [
      {
        id: "html_competency_scores_overview_legend",
        text: "Competency Scores Overview Legend",
        path: "assessment_reports/competency_report/html/competency_scores_overview/legend",
        locals: {},
        children: [
          {
            id: "html_competency_scores_overview_title",
            text: "Competency Scores Overview Title",
            path: "assessment_reports/competency_report/html/competency_scores_overview/competency_scores_overview_title",
            locals: {}
          },
          {
            id: "html_competency_scores_overview_custom_legend",
            text: "Custom Legend [Without Expected Score]",
            path: "assessment_reports/competency_report/html/competency_scores_overview/custom_legend",
            locals: {}
          },
          {
            id: "html_competency_scores_overview_generic_legend",
            text: "Generic Legend [With Expected Score]",
            path: "assessment_reports/competency_report/html/competency_scores_overview/generic_legend",
            locals: {}
          }
        ]
      },
      {
        id: "html_show_favourable_above_desired_range",
        text: "Scale [Above Desired Range is Favourable]",
        path: "assessment_reports/competency_report/html/competency_scores_overview/favourable_above_desired_range",
        locals: {
          competency_scores: "competency_scores"
        },
        children: [
          {
            id: "html_competency_scores_overview_custom_show_desired_ranges",
            text: "Show Desired Ranges",
            path: "assessment_reports/competency_report/html/competency_scores_overview/show_desired_range",
            locals: {
              width: "width",
              offset: "offset"
            }
          },
          {
            id: "html_competency_scores_overview_custom_hide_desired_ranges",
            text: "Hide Desired Ranges",
            path: "assessment_reports/competency_report/html/competency_scores_overview/hide_desired_range",
            locals: {
              width: "width",
              offset: "offset"
            }
          }
        ]
      },
      {
        id: "html_show_generic_scale",
        text: "Scale [Outside Range is Not Favourable]",
        path: "assessment_reports/competency_report/html/competency_scores_overview/favourable_within_desired_range",
        locals: {
          competency_scores: "competency_scores"
        },
        children: [
          {
            id: "html_competency_scores_overview_generic_show_desired_ranges",
            text: "Show Desired Ranges",
            path: "assessment_reports/competency_report/html/competency_scores_overview/show_desired_range",
            locals: {
              width: "width",
              offset: "offset"
            }
          },
          {
            id: "html_competency_scores_overview_generic_hide_desired_ranges",
            text: "Hide Desired Ranges",
            path: "assessment_reports/competency_report/html/competency_scores_overview/hide_desired_range",
            locals: {
              width: "width",
              offset: "offset"
            }
          }
        ]
      }
    ]
  },
  {
    id: "html_aptitude_score",
    text: "Show Cocubes Aptitude Score",
    path: "assessment_reports/competency_report/html/aptitude_score",
    children: []
  },
  {
    id: "html_score_scale",
    text: "Score Scale",
    path: "assessment_reports/score_scale",
    children: []
  },
  {
    id: "html_explanation_scores",
    text: "Explanation Scores",
    path: "assessment_reports/competency_report/html/explanation_scores",
    children: []
  },
  {
    id: "html_competencies_values_measured",
    text: "Competencies and Values Measured",
    path: "assessment_reports/competency_report/html/comptencies_values_measured",
    children: [
      {
        id: "html_custom_factor_block",
        text: "Custom Competency Block[Scores above range are favourable]",
        path: "assessment_reports/competency_report/html/custom_factor_block",
        locals: {
          step_competency_scores: "step_competency_scores"
        }
      },
      {
        id: "html_generic_factor_block",
        text: "Generic Competency Block[Scores outside range are not favourable]",
        path: "assessment_reports/competency_report/html/generic_factor_block",
        locals: {
          step_competency_scores: "step_competency_scores"
        }
      }
    ]
  },
  {
    id: "html_trait_scores_under_competencies",
    text: "Trait Scores Under Competencies",
    path: "assessment_reports/competency_report/html/trait_scores_under_competencies",
    children: [
      {
        id: "html_generic_competency_block_with_consistency_enabled",
        text: "Generic Factor Block[Outside Favourable Range is Not Favourable] With Factor Consistency Enabled",
        path: "assessment_reports/competency_report/html/generic_competency_consistency_enabled",
        locals: {}
      },
      {
        id: "html_generic_competency_block_with_consistency_disabled",
        text: "Generic Factor Block[Outside Favourable Range is Not Favourable] With Factor Consistency Disabled",
        path: "assessment_reports/competency_report/html/generic_competency_consistency_disabled",
        locals: {}
      },
      {
        id: "html_custom_competency_block_with_consistency_enabled",
        text: "Custom Factor Block[In and Above Favourable Range is Favourable] With Factor Consistency Enabled",
        path: "assessment_reports/competency_report/html/custom_competency_block_consistency_enabled",
        locals: {}
      },
      {
        id: "html_custom_competency_block_with_consistency_disabled",
        text: "Custom Factor Block[In and Above Favourable Range is Favourable] With Factor Consistency Disabled",
        path: "assessment_reports/competency_report/html/custom_competency_block_consistency_disabled",
        locals: {}
      }
    ]
  },
  {
    id: "html_functional_overview_section",
    text: "Functional Overview Sections",
    path: "assessment_reports/functional_report/html/functional_overview_section",
    children: []
  },
  {
    id: "html_objective_questions",
    text: "Objective Questions",
    path: "assessment_reports/functional_report/html/objective_questions",
    children: []
  },
  {
    id: "html_subjective_questions",
    text: "Subjective Questions",
    path: "assessment_reports/functional_report/html/subjective_questions",
    children: []
  },
  {
    id: "html_guidelines",
    text: "Guidelines for Candidate and Manager",
    path: "assessment_reports/competency_report/html/guidelines_for_candidate_and_manager",
    children: [
      {
        id: "html_guidelines_for_candidate",
        text: "For Candidate",
        path: "assessment_reports/competency_report/html/development_interview_guide_candidate",
        locals: {}
      },
      {
        id: "html_guidelines_for_candidate_manager",
        text: "For Manager",
        path: "assessment_reports/competency_report/html/development_interview_guide_manager",
        locals: {}
      }
    ]
  },
  {
    id: "html_common_footer_sections",
    text: "Footer",
    path: "shared/reports/html/common_footer_sections",
    children: [
      {
        id: "html_about_us",
        text: "About Us",
        path: "shared/reports/html/about_us",
        locals: {}
      },
      {
        id: "html_legal_disclaimer",
        text: "Legal Disclaimer",
        path: "shared/reports/html/legal_disclaimer",
        locals: {}
      }
    ]
  }
]
