--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
candidate_assessment_id: 54814
configuration: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  should_send_notifications: true
  any_scores_overwritten: false
  is_functional_assessment: false
  notifications_sent_at: '22_09_2015_14_53'
  regenerated_at:
  uploaded_at: '22_09_2015_14_53'
  regenerate_notify:
created_at: '2015-09-22T14:52:11+05:30'
id: 32174
report_configuration: !ruby/hash:ActiveSupport::HashWithIndifferentAccess {}
report_data: &1 !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  id: 32174
  candidate: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    name: Puja Burande
    email: puja.21.burande@gmail.com
    id: 52679
  assessment: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    id: 6620
    name: Fit Based Assessment 08-08-2015
    assessment_type: competency
    brand_partner: cocubes
  company: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    name: Jombay
    id: 2
  report_receiver: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    name: ''
    email: ''
  send_report_links_to_manager: false
  enable_recommendation: true
  enable_aggregate_competency_score: true
  enable_lie_detection: true
  enable_feedback: true
  enable_factor_consistency: true
  enable_post_assessment_guidelines: true
  enable_score_scale_section: true
  include_cocubes_scores_in_reoprts: true
  suitability_report_show_buckets_on_feedback: true
  competency_interpretation_guide: true
  include_subjective_questions: true
  include_objective_questions: true
  overall_score_bucket: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    id: 3
    name: Average (Low)
  overall_factor_score: 54.17
  overall_factor_score_rating: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    id: 3
    name: GREEN
    color: '#0EB156'
  consistency: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    enabled: true
    bucket_name: High
  suitability_competency_report_competency_scores_overview: true
  reliability: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    enabled: true
    bucket_name: Reliable
  lie_detection: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    bucket:
    description:
  s3_keys: !ruby/hash:ActiveSupport::HashWithIndifferentAccess {}
  report_email_recipients:
  candidate_stage: candidate
  candidate_assessment_id: 54814
  completed_at: 22/09/2015
  direct_predictor_scores: !ruby/hash:ActiveSupport::HashWithIndifferentAccess {}
  post_assessment_guidelines: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    Assertiveness: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      pass: false
      body: Describe a situation where your colleague did not agree to your opinion. How did you convince him/her?
      factor_type: Suitability::Factor
    Agreeableness: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      pass: false
      body: When you have difference of opinion with your colleague, do you get convinced easily?
      factor_type: Suitability::Factor
    Adaptability: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      pass: true
      body: Give us an example where you had to face frequent changes. How did you deal with it?
      factor_type: Suitability::Factor
    Compliance: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      pass: true
      body: Everyone has to bend or break rules sometimes.  Give few examples when you had to do this.
      factor_type: Suitability::Factor
  guidelines_for_candidate_manager: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    Assertiveness: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      pass: false
      body: You could consider encouraging him/her to speak up his/her mind, defend opinions in groups to help gain confidence.
      factor_type: Suitability::Factor
    Agreeableness: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      pass: false
      body: You could try to get him/her to list the pros and cons of his/her firm stand so that he/she is more open to considering the opinions of others. You may also want to encourage him/her to consider the opinions of at least two other team members before he/she sticks to his/her own opinion.
      factor_type: Suitability::Factor
    Adaptability: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      pass: true
      body: He/she could be more effective in dynamic environments as compared to others. Hence, you could consider assigning to him/her such projects or responsibilities as they come by.
      factor_type: Suitability::Factor
    Compliance: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      pass: true
      body: Try to ensure that he/she does not stress himself/herself or the team while insisting adherence to rules and procedures.
      factor_type: Suitability::Factor
  enable_functional_overview_section: true
  subjective_items: !ruby/hash:ActiveSupport::HashWithIndifferentAccess {}
  objective_items: !ruby/hash:ActiveSupport::HashWithIndifferentAccess {}
  section_wise_objective_item_scores: !ruby/hash:ActiveSupport::HashWithIndifferentAccess {}
  functional_items: !ruby/hash:ActiveSupport::HashWithIndifferentAccess {}
  include_functional_traits_in_aggregate_scores: false
  objective_score: 0.0
  html_suitability_reports_scale_description_page: true
  pdf_suitability_reports_scale_description_page: true
  competency_score_rating_on_overall_score: true
  plain_score_rating_on_overall_score: true
  enable_competency_desired_ranges: true
  enable_interview_and_development_guide_both: false
  show_favourable_above_desired_range: true
  competency_scores: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    PayTM Karo: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      id: 2525
      score: 54.17
      grade: Average (Low)
      grade_uid: BrXyV
      factor_ids:
      - 28
      - 16
      - 39
      - 1
      factor_scores: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        Adaptability: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
          type: Suitability::Factor
          factor_score_id: 746025
          factor_id: 28
          score: 100.0
          pass: true
          scale: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
            from_norm_bucket_uid: ygMKO
            to_norm_bucket_uid: pZQeOjio
          norm_bucket: High
          norm_bucket_uid: pZQeOjio
          consistency_bucket: High
          description: Usually uncomplainingly adjusts to changing environments; more likely to enjoy change and look forward to it; tends to get easily accustomed to change; almost always flexible at work
          factor_definition: Degree to which an individual is open to new experiences, ideas, feedback and change
        Agreeableness: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
          type: Suitability::Factor
          factor_score_id: 746023
          factor_id: 16
          score: 20.0
          pass: false
          scale: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
            from_norm_bucket_uid: BrXyV
            to_norm_bucket_uid: pZQeOjio
          norm_bucket: Low
          norm_bucket_uid: vBUZs
          consistency_bucket: Average
          description: Often takes time to be convinced; may not always be open to listening to others ideas or suggestions; usually does not easily agree with group decisions without debate; more likely to perceive his/her own views as more justified than those of others
          factor_definition: Tendency to agree easily with others (High scores indicate a tendency to agree easily, Low scores indicate a tendency to be stubborn)
        Compliance: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
          type: Suitability::Factor
          factor_score_id: 746026
          factor_id: 39
          score: 100.0
          pass: true
          scale: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
            from_norm_bucket_uid: ygMKO
            to_norm_bucket_uid: pZQeOjio
          norm_bucket: High
          norm_bucket_uid: pZQeOjio
          consistency_bucket: High
          description: Tend to follow all guidelines meticulously; almost always rule-conscious; often lives by ethics and morals; tends to get irritated if policies and guidelines are not adhered to; may come across as less flexible at times
          factor_definition: Degree to which an individual adheres to rules and regulations
        Assertiveness: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
          type: Suitability::Factor
          factor_score_id: 746024
          factor_id: 1
          score: 22.17
          pass: false
          scale: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
            from_norm_bucket_uid: ygMKO
            to_norm_bucket_uid: pZQeOjio
          norm_bucket: Low
          norm_bucket_uid: vBUZs
          consistency_bucket: Above Average
          description: Less likely to be frank and insistent; tends to be indirect when expressing feelings, needs and ideas; more likely to avoid confrontation; may not feel the need to express his/her opinions in most situations; less likely to voice his/her criticism
          factor_definition: Tendency to be firm, frank and insistent
      from_norm_bucket_uid: vBUZs
      to_norm_bucket_uid: pZQeOjio
  aggregate_competency_score_bucket: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    id: 3
    name: Average (Low)
  aggregate_competency_score: 54.17
  aggregate_competency_score_rating: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    id: 2
    name: AMBER
    color: '#CD6212'
  hexagons_page_competency: true
  trait_scores_competency: true
  interview_guide: true
  cocubes_score: 12.0
  cocubes_max_score: 30.0
  cocubes_percentage_score: 40.0
s3_keys: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  pdf: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    bucket: report_pdfs_staging_internal
    key: suitability_reports/pdf/puja-burande-jombay-32174.pdf
  html: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    bucket: report_pdfs_staging_internal
    key: suitability_reports/html/puja-burande-jombay-32174.html
  feedback: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    bucket: report_pdfs_staging_internal
    key: suitability_reports/feedback/feedback-puja-burande-jombay-32174.html
status: uploaded
updated_at: '2015-09-22T14:53:35+05:30'
report_hash: *1
