development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: recruiters_development
  pool: 5
  username: root
  password: abc123
  socket: /var/run/mysqld/mysqld.sock

staging_dennis:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: recruiters_dennis
  pool: 5
  username: root
  password: abc123
  socket: /var/run/mysqld/mysqld.sock

staging_steve:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: recruiters_steve
  pool: 5
  username: root
  password: abc123
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: recruiters_production
  pool: 5
  username: root
  password: abc123
  socket: /var/run/mysqld/mysqld.sock
