:mrf:
  :competency:
    :html: 
      :sections: [
        {
          id: "cover_page",
          text: "Cover page",
          path: "mrf/assessments/reports/competency_report/html/page1",
          children: [
            {
              id: "numerical_aggregate_score",
              text: "Numerical Aggregate Score",
              path: "mrf/assessments/reports/competency_report/html/numerical_aggregate_score",
              locals: {}
            },
            {
              id: "show_completion_status",
              text: "Completion Status",
              path: "mrf/assessments/reports/competency_report/html/show_completion_status",
              locals: {}
            },
            {
              id: "mrf_report_cover",
              text: "Report Cover",
              path: "mrf/assessments/reports/competency_report/html/mrf_report_cover",
              locals: {}
            }
          ]
        },
        {
          id: "360_degree_scores_competencies",
          text: "360 Degree Scores Competencies",
          path: "mrf/assessments/reports/competency_report/html/scores_competencies",
          children: [
            {
              id: "competency_classic_graph",
              text: "Competency Classic Graph",
              path: "mrf/assessments/reports/competency_report/html/competency_classic_graph.html.haml",
              locals: {}
            }
          ]
        },
        {
          id: "360_degree_scores_traits_under_competencies",
          text: "360 Degree Scores Traits Under Competencies",
          path: "mrf/assessments/reports/competency_report/html/scores_traits_competencies",
          children: []
        },
        {
          id: "strength_and_areas_of_improvement",
          text: "Strength and Areas of Improvement",
          path: "mrf/assessments/reports/competency_report/html/strength_improvement_areas",
          children: []
        },
        {
          id: "360_degree_competencies_scores_in_descending_order",
          text: "360 Degree Competencies Score in Descending Order",
          path: "mrf/assessments/reports/competency_report/html/competencies_descending_order",
          children: []
        },
        {
          id: "360_degree_traits_scores_in_descending_order",
          text: "360 Degree Traits Score in Descending Order",
          path: "mrf/assessments/reports/competency_report/html/competencies_traits_descending_order",
          children: []
        },
        {
          id: "data_points_on_360_degree_scores_competencies",
          text: "Data Points on 360 Degree Scores",
          path: "mrf/assessments/reports/competency_report/html/competency_wise_frequency_data_points",
          children: [
            {
              id: "competencies_textual_data_points",
              text: "Competencies Textual Data Points",
              path: "mrf/assessments/reports/competency_report/html/competencies_textual_data_points",
              locals: {
                competency_scores: "competency_scores"
              }
            },
            {
              id: "competency_wise_best_worst_scores",
              text: "Competencywise best and worst score",
              path: "mrf/assessments/reports/competency_report/html/competency_wise_best_worst_scores",
              locals: {
                competency: "competency",
                competency_scores: "competency_scores"
              }
            },
            {
              id: "competencies_descending_order",
              text: "Competencies in Descending Order",
              path: "mrf/assessments/reports/competency_report/html/descending_overall_competency_score",
              locals: {
                competency: "competency",
                competency_scores: "competency_scores"
              }
            },
            {
              id: "descending_average_competency_rating",
              text: "Average Competency Rating in Descending Order",
              path: "mrf/assessments/reports/competency_report/html/descending_average_competency_rating.html.haml",
              locals: {
                competency: "competency",
                competency_scores: "competency_scores"
              }
            },
            {
              id: "competency_frequency_rating_table",
              text: "Frequency Rating Table",
              path: "mrf/assessments/reports/competency_report/html/frequency_rating_table",
              locals: {
                role_wise_scores : "competency_scores{:role_wise_scores}",
                trait_wise: "false",
                graph_buckets: "@competency_graph_buckets"
              }
            }
          ]
        },
        {
          id: "data_points_on_360_degree_scores_traits_under_competencies",
          text: "Data Points on 360 Scores Traits Under Competencies",
          path: "mrf/assessments/reports/competency_report/html/trait_wise_frequency_data_points",
          children: [
            {
              id: "traits_textual_data_points",
              text: "Traits Textual Data Points",
              path: "mrf/assessments/reports/competency_report/html/traits_textual_data_points",
              locals: {
                trait_score: "trait_score"
              }
            },
            {
              id: "trait_wise_best_worst_scores",
              text: "Traitwise Best and Worst Score",
              path: "mrf/assessments/reports/competency_report/html/trait_wise_best_worst_scores",
              locals: {
                trait_score: "trait_score"
              }
            },
            {
              id: "descending_trait_wise_overall_score",
              text: "Trait Wise Overall Score in descending order",
              path: "mrf/assessments/reports/competency_report/html/descending_trait_wise_overall_score",
              locals: {
                trait_score: "trait_score"
              }
            },
            {
              id: "descending_trait_wise_average_rating",
              text: "Trait wise average rating in descending order",
              path: "mrf/assessments/reports/competency_report/html/descending_trait_wise_average_rating",
              locals: {
                trait_score: "trait_score"
              }
            },
            {
              id: "frequency_rating_table",
              text: "Frequency Rating Table",
              path: "mrf/assessments/reports/competency_report/html/frequency_rating_table",
              locals: {
                role_wise_scores: "trait_score{:role_wise_scores}",
                trait_wise: "true",
                graph_buckets: "@trait_graph_buckets" 
              }
            }
          ]
        },
        {
          id: "data_points_on_360_degree_scores_questions",
          text: "Data Points on 360 Degree Scores Questions",
          path: "mrf/assessments/reports/competency_report/html/competencies_data_points_questions",
          children: []
        },
        {
          id: "response_distribution_on_questions",
          text: "Response Distribution on Questions",
          path: "mrf/assessments/reports/competency_report/html/response_distribution",
          children: []
        },
        {
          id: "competencies_measured",
          text: "Competencies Measured",
          path: "mrf/assessments/reports/competency_report/html/page2",
          children: []
        },
        {
          id: "competencies_with_360_degree_scores",
          text: "Competencies with 360 Degree Scores",
          path: "mrf/assessments/reports/competency_report/html/page3",
          children: []
        },
        {
          id: "data_points_about_360_degree_scores_competencies",
          text: "Data Points on 360 Degree Scores Competencies",
          path: "mrf/assessments/reports/competency_report/html/competency_distribution_data_points",
          children: [
            {
              id: "stakeholder_level_breakdown_at_competency_level",
              text: "Stakeholder Breakdown at Competency Level",
              path: "mrf/assessments/reports/competency_report/html/mrf_stakeholder_level_breakdown_at_competency_level",
              locals: {
                competency_score: "competency_score"
              }
            }
          ]
        },
        {
          id: "data_points_about_360_degree_scores_traits_under_competencies",
          text: "Data Points on 360 Degree Scores Traits Under Competencies",
          path: "mrf/assessments/reports/competency_report/html/trait_distribution_data_points",
          children: [
            {
              id: "stakeholder_level_breakdown_at_trait_level",
              text: "Stakeholder Level Breakdown and Trait Level",
              path: "mrf/assessments/reports/competency_report/html/mrf_stakeholder_level_breakdown_at_trait_level",
              locals: {
                trait_score: "trait_score"
              }
            }
          ]
        },
        {
          id: "data_points_on_360_degree_scores_of_competencies",
          text: "Data Points on 360 Degree Scores of Compentencies",
          path: "mrf/assessments/reports/competency_report/html/page4",
          children: [
            {
              id: "competency_data_points",
              text: "Competency Data Points",
              path: "mrf/assessments/reports/competency_report/html/competency_data_points",
              locals: {
                role_wise_scores: "@report.report_data{:role_wise_scores}"
              }
            }
          ]
        },
        {
          id: "traits_with_360_degree_scores",
          text: "Traits with 360 Degree Scores",
          path: "mrf/assessments/reports/competency_report/html/page5",
          children: []
        },
        {
          id: "data_points_on_360_degree_scores_of_traits",
          text: "Data Points on 360 Scores of Traits",
          path: "mrf/assessments/reports/competency_report/html/page6",
          children: []
        },
        {
          id: "stakeholder_comments_on_traits_under_various_competencies",
          text: "Stakeholder comments on traits under various competencies",
          path: "mrf/assessments/reports/competency_report/html/page7",
          children: []
        },
        {
          id: "responses_to_other_questions",
          text: "Response to Other Questions",
          path: "mrf/assessments/reports/competency_report/html/page8",
          children: []
        },
        {
          id: "summary_of_360_degree_feedback",
          text: "Summary of 360 Degree Feedback",
          path: "mrf/assessments/reports/competency_report/html/page9",
          children: []
        },
        {
          id: "about_us",
          text: "About Us",
          path: "shared/reports/html/about_us",
          children: []
        },
        {
          id: "legal_disclaimer",
          text: "Legal Disclaimer",
          path: "shared/reports/html/legal_disclaimer",
          children: []
        }
]
