development: &dev
  mrf:
    competency:
      assessment_id: 322
      candidate_id: 51216
      id: 981
    fit:
      assessment_id: 324
      candidate_id: 51675
      id: 987
staging_internal:
  mrf:
    competency:
      assessment_id: 322
      candidate_id: 51216
      id: 981
    fit:
      assessment_id: 324
      candidate_id: 51675
      id: 987
staging:
  mrf:
    competency:
      assessment_id: 0
      candidate_id: 0
      id: 0
    fit:
      assessment_id: 0
      candidate_id: 0
      id: 0
production:
  mrf:
    competency:
      assessment_id: 0
      candidate_id: 0
      id: 0
    fit:
      assessment_id: 0
      candidate_id: 0
      id: 0