:suitability:
  :competency:
    :html: &html
      :sections: [
        {
          id: "html_cover_page",
          text: "Cover Page",
          path: "assessment_reports/competency_report/html/cover_page",
          children: [
            {
              id: "html_aggregate_competency_score",
              text: "Aggregate Competency Scores",
              path: "assessment_reports/competency_report/html/aggregate_competency_score",
              children: [
                {
                  id: "html_color_band",
                  text: "Color Band",
                  path: "assessment_reports/competency_report/html/competency_score_rating_on_overall_score",
                  locals: {},
                  children: []
                },
                {
                  id: "html_functional_items_legend",
                  text: "Functional Items Legend",
                  path: "assessment_reports/competency_report/html/functional_items_legend",
                  children: [
                    {
                      id: "html_include_functional_legend",
                      text: "Include Functional Items Legend",
                      path: "assessment_reports/competency_report/html/include_functional_legend",
                      locals: {}
                    },
                    {
                      id: "html_exculde_functional_legend",
                      text: "Exclude Functional Items Legend",
                      path: "assessment_reports/competency_report/html/exclude_functional_legend",
                      locals: {}
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          id: "html_competency_interpretation_guide",
          text: "Competency Interpretation Guidelines",
          path: "assessment_reports/competency_report/html/competency_interpretation_guide",
          children: []
        },
        {
          id: "html_aptitude_score",
          text: "Show Cocubes Aptitude Score",
          path: "assessment_reports/competency_report/html/aptitude_score",
          children: []
        },
        {
          id: "html_score_scale",
          text: "Score Scale",
          path: "assessment_reports/score_scale",
          children: []
        },
        {
          id: "html_explanation_scores",
          text: "Exaplanation Scores",
          path: "assessment_reports/competency_report/html/explanation_scores",
          children: []
        },
        {
          id: "html_competency_scores_overview",
          text: "Competency Scores Overview",
          path: "assessment_reports/competency_report/html/competency_scores_overview",
          children: [
            {
              id: "html_custom_legend",
              text: "Custom Legend[Without Expected Score]",
              path: "assessment_reports/competency_report/html/custom_legend",
              locals: {}
            },
            {
              id: "html_generic_legend",
              text: "Generic Legend[With Expected Score]",
              path: "assessment_reports/competency_report/html/generic_legend",
              locals: {}
            },
            {
              id: "html_show_favourable_above_desired_range",
              text: "Scale[Above Desired Range is Favourable]",
              path: "assessment_reports/competency_report/html/show_favourable_above_desired_range",
              locals: {
                competency_scores: "competency_scores"
              }
            },
            {
              id: "html_show_generic_scale",
              text: "Scale[Outside Range is Not Favourable]",
              path: "assessment_reports/competency_report/html/show_generic_scale",
              locals: {
                competency_scores: "competency_scores"
              }
            }
          ]
        },
        {
          id: "html_competencies_values_measured",
          text: "Competencies and Values Measured",
          path: "assessment_reports/competency_report/html/comptencies_values_measured",
          children: [
            {
              id: "html_custom_factor_block",
              text: "Custom Factor Block[Scores above range are shown as favourable]",
              path: "assessment_reports/competency_report/html/custom_factor_block",
              locals: {
                step_competency_scores: "step_competency_scores"
              }
            },
            {
              id: "html_generic_factor_block",
              text: "Generic Factor Block[Scores above and below range are shown as not favourable]",
              path: "assessment_reports/competency_report/html/generic_factor_block",
              locals: {
                step_competency_scores: "step_competency_scores"
              }
            }
          ]
        },
        {
          id: "html_trait_scores_under_competencies",
          text: "Trait Scores Under Competencies",
          path: "assessment_reports/competency_report/html/trait_scores_under_competencies",
          children: [
            {
              id: "html_generic_competency_block",
              text: "Generic Competency Block[Outside Favourable Range is Not Favourable]",
              path: "assessment_reports/competency_report/html/generic_competency",
              locals: {
              }
            },
            {
              id: "html_custom_competency_block",
              text: "Custom Competency Block[In and Above Favourable Range is Favourable]",
              path: "assessment_reports/competency_report/html/custom_competency_block",
              locals: {
              }
            }
          ]
        },
        {
          id: "html_functional_overview_section",
          text: "Functional Overview Sections",
          path: "assessment_reports/functional_report/html/functional_overview_section",
          children: []
        },
        {
          id: "html_objective_questions",
          text: "Objective Questions",
          path: "assessment_reports/functional_report/html/objective_questions",
          children: []
        },
        {
          id: "html_subjective_questions",
          text: "Subjective Questions",
          path: "assessment_reports/functional_report/html/subjective_questions",
          children: []
        },
        {
          id: "html_guidelines",
          text: "Guidelines for Candidate and Manager",
          path: "assessment_reports/competency_report/html/guidelines_for_candidate_and_manager",
          children: [
            {
              id: "html_guidelines_for_candidate",
              text: "For Candidate",
              path: "assessment_reports/competency_report/html/development_interview_guide_candidate",
              locals: {}
            },
            {
              id: "html_guidelines_for_candidate_manager",
              text: "For Manager",
              path: "assessment_reports/competency_report/html/development_interview_guide_manager",
              locals: {}
            }
          ]
        },
        {
          id: "html_common_footer_sections",
          text: "Footer",
          path: "shared/reports/html/common_footer_sections",
          children: [
            {
              id: "html_about_us",
              text: "About Us",
              path: "shared/reports/html/about_us",
              locals: {}
            },
            {
              id: "html_legal_disclaimer",
              text: "Legal Disclaimer",
              path: "shared/reports/html/legal_disclaimer",
              locals: {}
            }
          ]
        }
      ]
    :pdf:
      :sections: [
        {
          id: "pdf_cover_page",
          text: "Cover Page",
          path: "assessment_reports/competency_report/pdf/cover_page",
          children: []
        },
        {
          id: "pdf_competency_report_guideline",
          text: "Competency report guideline",
          path: "assessment_reports/competency_report/pdf/competency_report_guideline",
          children: []
        },
        {
          id: "pdf_aptitude_score",
          text: "Show Cocubes Aptitude Score",
          path: "assessment_reports/competency_report/pdf/aptitude_score",
          children: []
        },
        {
          id: "pdf_score_scale",
          text: "Score Scale",
          path: "assessment_reports/score_scale",
          children: []
        },
        {
          id: "pdf_explanation_scores",
          text: "Scores Exaplanation",
          path: "assessment_reports/competency_report/pdf/explanation_scores",
          children: []
        },
        {
          id: "pdf_custom_competency_score_overview",
          text: "Custom Competency Score Overview",
          path: "assessment_reports/competency_report/pdf/custom_competency_score_overview",
          children: []
        },
        {
          id: "pdf_competencies_values_measured",
          text: "Competencies Values Measured",
          path: "assessment_reports/competency_report/pdf/compentencies_values_measured",
          children: 
          [
            {
              id: "pdf_custom_factor_block",
              text: "Custom Factor Block[Scores above range are shown as favourable]",
              path: "assessment_reports/competency_report/pdf/custom_factor_block",
              locals: {
                step_competency_scores: "step_competency_scores"
              }
            },
            {
              id: "pdf_generic_factor_block",
              text: "Generic Factor Block[Scores above and below range are shown as not favourable]",
              path: "assessment_reports/competency_report/pdf/generic_factor_block",
              locals: {
                step_competency_scores: "step_competency_scores"
              }
            }
          ]
        },
        {
          id: "pdf_factor_scores_unders_competencies",
          text: "Factor Scores Under Competencies",
          path: "assessment_reports/competency_report/pdf/factor_scores_under_competencies",
          children: [
            {
              id: "pdf_custom_competency",
              text: "Custom Competency Block [Above range is Favourable]",
              path: "assessment_reports/competency_report/pdf/custom_competency",
              locals: {
                competency_name: "competency_name",
                competency_data: "competency_data",
                factor_scores: "factor_scores",
                step: "step"
              }
            },
            {
              id: "pdf_generic_competency",
              text: "competency Block [Outside Range is not Favourable]",
              path: "assessment_reports/competency_report/pdf/generic_competency",
              locals: {
                competency_name: "competency_name",
                competency_data: "competency_data",
                factor_scores: "factor_scores",
                step: "step"
              }
            }
          ]
        },
        {
          id: "pdf_functional_overview_sections",
          text: "Functional Overview Section",
          path: "assessment_reports/functional_report/pdf/functional_overview_section",
          children: []
        },
        {
          id: "pdf_objective_questions",
          text: "Objective Questions",
          path: "assessment_reports/functional_report/pdf/objective_questions",
          children: []
        },
        {
          id: "pdf_subjective_questions",
          text: "Subjective Questions",
          path: "assessment_reports/functional_report/pdf/subjective_questions",
          children: []
        },
        {
          id: "pdf_miscellaneous_factors",
          text: "Miscellaneous Factors",
          path: "assessment_reports/competency_report/pdf/miscellaneous_factors",
          children: []
        },
        {
          id: "pdf_development_interview_guide_candidate",
          text: "Developemnt Interview Guide For Candidate",
          path: "assessment_reports/competency_report/pdf/development_interview_guide_candidate",
          children: []
        },
        {
          id: "pdf_development_interview_guide_manager",
          text: "Developemnt Interview Guide For Manager",
          path: "assessment_reports/competency_report/pdf/development_interview_guide_manager",
          children: []
        },
        {
          id: "pdf_common_footer_sections",
          text: "Footer",
          path: "shared/reports/pdf/common_footer_sections",
          children: [
            {
              id: "html_about_us",
              text: "About Us",
              path: "shared/reports/pdf/about_us",
              locals: {}
            },
            {
              id: "html_legal_disclaimer",
              text: "Legal Disclaimer",
              path: "shared/reports/pdf/legal_disclaimer",
              locals: {}
            }
          ]
        }
      ]
  :fit:
    :html: &html
      :sections: [
        {
          id: "html_cover_page",
          text: "Cover Page",
          path: "assessment_reports/fit_report/html/page1",
          children: [
            {
              id: "html_enable_recommendation",
              text: "Enable Recommendation",
              path: "assessment_reports/fit_report/html/enable_recommendation",
              children: [
                {
                  id: "html_aggregate_score",
                  text: "Aggregate Score",
                  path: "assessment_reports/fit_report/html/aggregat_score_recommendation",
                  locals: {}
                },
                {
                  id: "html_color_band",
                  text: "Color Band",
                  path: "assessment_reports/fit_report/html/color_band",
                  locals: {}
                }
              ]
            },
            {
              id: "html_assessment_details",
              text: "Assessment Details [Name and Completion Date]",
              path: "assessment_reports/fit_report/html/assessment_details",
              locals: {}
            }
          ]
        },
        {
          id: "html_score_scale",
          text: "Score Scale",
          path: "assessment_reports/score_scale",
          children: []
        },
        {
          id: "html_traits_measured_in_this_assessment",
          text: "Traits Measured In This Assessment",
          path: "assessment_reports/fit_report/html/page2",
          children: []
        },
        {
          id: "html_scores_of_traits_measured_in_this_assessment",
          text: "Scores of Traits Measured In this Assessment",
          path: "assessment_reports/fit_report/html/page3",
          children: [
            {
              id: "html_enable_factor_score_consistency",
              text: "Enable Factor Score Consistency",
              path: "assessment_reports/fit_report/html/enable_factor_consistency",
              locals: {
                factor_score: "factor_score"
              }
            }
          ]
        },
        {
          id: "html_scores_of_functional_traits_measured_in_assessment",
          text: "Scores of Functional Traits",
          path: "assessment_reports/fit_report/html/scores_of_functional_traits",
          children: []
        },
        {
          id: "html_functional_overview_section",
          text: "Functional Overview Section",
          path: "assessment_reports/functional_report/html/functional_overview_section",
          children: []
        },
        {
          id: "html_objective_questions",
          text: "Objective Questions",
          path: "assessment_reports/functional_report/html/objective_questions",
          children: []
        },
        {
          id: "html_subjective_questions",
          text: "Subjective Questions",
          path: "assessment_reports/functional_report/html/subjective_questions",
          children: []
        },
        {
          id: "html_miscellaneous_factors",
          text: "Miscellaneous Factors",
          path: "assessment_reports/fit_report/html/page4",
          children: []
        },
        {
          id: "html_development_guide_for_assessment_taker",
          text: "Developemnt Guide For Assessment Taker",
          path: "assessment_reports/fit_report/html/page5",
          children: []
        },
        {
          id: "html_guidelines_for_candidate_manager",
          text: "Developemnt Guide For Candidate Manager",
          path: "assessment_reports/fit_report/html/page6",
          children: []
        },
        {
          id: "html_about_us",
          text: "About Us",
          path: "shared/reports/html/about_us",
          children: []
        },
        {
          id: "html_legal_disclaimer",
          text: "Legal Disclaimer",
          path: "shared/reports/html/legal_disclaimer",
          children: []
        }
      ]
    :pdf:
      :sections: [
        {
          id: "pdf_cover_page",
          text: "PDF_FIT_Cover Page",
          path: "assessment_reports/fit_report/pdf/page1",
          children: []
        },
        {
          id: "pdf_score_scale",
          text: "Score Scale",
          path: "assessment_reports/score_scale",
          children: []
        },
        {
          id: "pdf_traits_in_this_assessment",
          text: "Traits Measured In This Assessment",
          path: "assessment_reports/fit_report/pdf/page2",
          children: []
        },
        {
          id: "pdf_scores_of_traits_measured",
          text: "Scores Of Traits Measured",
          path: "assessment_reports/fit_report/pdf/page3",
          children: []
        },
        {
          id: "pdf__scores_of_functional_traits",
          text: "Scores of Functional Traits",
          path: "assessment_reports/fit_report/pdf/scores_of_functional_traits",
          children: []
        },
        {
          id: "pdf_functional_overview_sections",
          text: "Functional Overview Section",
          path: "assessment_reports/functional_report/pdf/functional_overview_section",
          children: []
        },
        {
          id: "pdf_objective_questions",
          text: "Objective Questions",
          path: "assessment_reports/functional_report/pdf/objective_questions",
          children: []
        },
        {
          id: "pdf_subjective_questions",
          text: "Subjective Questions",
          path: "assessment_reports/functional_report/pdf/subjective_questions",
          children: []
        },
        {
          id: "pdf_miscellaneous_factors",
          text: "Miscellaneous Factors",
          path: "assessment_reports/fit_report/pdf/page4",
          children: []
        },
        {
          id: "pdf_development_interview_guide_candidate",
          text: "Developement Guide For Assessment Taker",
          path: "assessment_reports/fit_report/pdf/page5",
          children: []
        },
        {
          id: "pdf_development_interview_guide_manager",
          text: "Guidelines For Assessment Taker Manager",
          path: "assessment_reports/fit_report/pdf/page6",
          children: []
        },
        {
          id: "pdf_common_footer_sections",
          text: "Footer",
          path: "shared/reports/pdf/common_footer_sections",
          children: [
            {
              id: "pdf_about_us",
              text: "About Us",
              path: "shared/reports/pdf/about_us",
              locals: {}
            },
            {
              id: "pdf_legal_disclaimer",
              text: "Legal Disclaimer",
              path: "shared/reports/pdf/legal_disclaimer",
              locals: {}
            }
          ]
        }
      ]
  :jq:
    :html:
      <<: *html
    :pdf:
      <<: *html