development: &dev
  bucket_name : "companiesdevelopment"
test: &test
  <<: *dev

staging:
  bucket_name : "companiesstaging"

staging_internal:
  bucket_name : "companiesstaginginternal"

production:
  bucket_name : "companiesproduction"
